import { parseProject, type FlickProject } from '../project.ts';
import type { FlickProjectV2 } from './project.ts';
import { migrateV1ToV2 } from '../migrations/v1-to-v2.ts';
import { assertNoCredentialFields } from '../secrets.ts';

function invariant(c:unknown,m:string):asserts c { if(!c) throw new TypeError(m); }
function record(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v)}
function finite(v:unknown,path:string):void{if(typeof v==='number')invariant(Number.isFinite(v),`${path} must be finite`);else if(Array.isArray(v))v.forEach((x,i)=>finite(x,`${path}[${i}]`));else if(record(v))for(const [k,x] of Object.entries(v))finite(x,`${path}.${k}`)}
function strings(v:unknown,path:string):string[]{invariant(Array.isArray(v)&&v.every(x=>typeof x==='string'&&x.length>0),`${path} must be string array`);return v as string[]}
function validateGenerativeExtensions(input:Record<string,unknown>,assetIds:Set<string>):void{
 const generations=input.generationRecords;if(generations!==undefined){invariant(Array.isArray(generations),'generationRecords must be array');const ids=new Set<string>();for(let i=0;i<generations.length;i++){const g=generations[i];invariant(record(g),`generationRecords[${i}] must be object`);invariant(typeof g.id==='string'&&g.id.length>0,`generationRecords[${i}].id required`);invariant(!ids.has(g.id),`duplicate generation id ${g.id}`);ids.add(g.id);invariant(['image','image-edit','layer-decomposition','inpaint','depth','video','audio'].includes(String(g.kind)),`generation ${g.id} kind invalid`);invariant(typeof g.provider==='string'&&g.provider.length>0,`generation ${g.id} provider required`);invariant(typeof g.model==='string'&&g.model.length>0,`generation ${g.id} model required`);invariant(typeof g.requestHash==='string'&&g.requestHash.length>0,`generation ${g.id} requestHash required`);invariant(typeof g.createdAt==='string'&&g.createdAt.length>0,`generation ${g.id} createdAt required`);const ins=strings(g.inputAssetIds,`generation ${g.id}.inputAssetIds`),outs=strings(g.outputAssetIds,`generation ${g.id}.outputAssetIds`);for(const id of [...ins,...outs])invariant(assetIds.has(id),`generation ${g.id} references missing asset ${id}`);invariant(record(g.parameters),`generation ${g.id}.parameters must be object`);finite(g.parameters,`generation ${g.id}.parameters`);finite(g.usage,`generation ${g.id}.usage`);if(typeof g.seed==='number')invariant(Number.isFinite(g.seed),`generation ${g.id}.seed must be finite`);}}
 const scenes=input.generatedScenes;if(scenes!==undefined){invariant(Array.isArray(scenes),'generatedScenes must be array');const ids=new Set<string>();for(let i=0;i<scenes.length;i++){const s=scenes[i];invariant(record(s),`generatedScenes[${i}] must be object`);invariant(typeof s.id==='string'&&s.id.length>0,`generatedScenes[${i}].id required`);invariant(!ids.has(s.id),`duplicate generated scene id ${s.id}`);ids.add(s.id);invariant(typeof s.sourceAssetId==='string'&&assetIds.has(s.sourceAssetId),`generated scene ${s.id} source asset missing`);for(const id of strings(s.layerAssetIds,`generated scene ${s.id}.layerAssetIds`))invariant(assetIds.has(id),`generated scene ${s.id} references missing asset ${id}`);for(const key of ['depthAssetId','cleanPlateAssetId'] as const){const id=s[key];if(id!==undefined)invariant(typeof id==='string'&&assetIds.has(id),`generated scene ${s.id} references missing asset ${String(id)}`);}invariant(typeof s.decompositionProvider==='string'&&s.decompositionProvider.length>0,`generated scene ${s.id} decomposition provider required`);invariant(Array.isArray(s.layers),`generated scene ${s.id}.layers must be array`);const layerIds=new Set<string>();for(const layer of s.layers){invariant(record(layer)&&typeof layer.id==='string'&&layer.id.length>0,`generated scene ${s.id} layer id required`);invariant(!layerIds.has(layer.id),`duplicate generated scene layer ${layer.id}`);layerIds.add(layer.id);invariant(typeof layer.assetId==='string'&&assetIds.has(layer.assetId),`generated scene ${s.id} layer asset missing`);finite(layer.z,`generated scene ${s.id}.${layer.id}.z`);invariant(record(layer.bounds),`generated scene ${s.id}.${layer.id}.bounds invalid`);finite(layer.bounds,`generated scene ${s.id}.${layer.id}.bounds`);invariant(typeof layer.bounds.width==='number'&&layer.bounds.width>0&&typeof layer.bounds.height==='number'&&layer.bounds.height>0,`generated scene ${s.id}.${layer.id} bounds must be positive`);if(layer.confidence!==undefined)invariant(typeof layer.confidence==='number'&&Number.isFinite(layer.confidence)&&layer.confidence>=0&&layer.confidence<=1,`generated scene ${s.id}.${layer.id} confidence invalid`);if(layer.depthRange!==undefined){invariant(Array.isArray(layer.depthRange)&&layer.depthRange.length===2,`generated scene ${s.id}.${layer.id} depth range invalid`);finite(layer.depthRange,`generated scene ${s.id}.${layer.id}.depthRange`);}if(layer.meshAssetId!==undefined)invariant(typeof layer.meshAssetId==='string'&&assetIds.has(layer.meshAssetId),`generated scene ${s.id}.${layer.id} mesh asset missing`);}invariant(Array.isArray(s.diagnostics)&&s.diagnostics.every(x=>typeof x==='string'),`generated scene ${s.id}.diagnostics must be strings`);}}
}
export function parseProjectV2(input:unknown):FlickProjectV2 {
 invariant(typeof input==='object'&&input!==null&&!Array.isArray(input),'project must be an object');
 const p=input as Partial<FlickProjectV2>;invariant(p.version===2,'project.version must be 2');invariant(typeof p.id==='string'&&p.id.length>0,'id must be non-empty');invariant(typeof p.name==='string'&&p.name.length>0,'name must be non-empty');invariant(p.format&&Number.isInteger(p.format.width)&&Number.isInteger(p.format.height),'format is invalid');invariant(Array.isArray(p.assets),'assets must be array');invariant(Array.isArray(p.compositions),'compositions must be array');invariant(typeof p.rootCompositionId==='string','rootCompositionId required');invariant(p.compositions.some(c=>c.id===p.rootCompositionId),'root composition missing');invariant(Array.isArray(p.audioBuses),'audioBuses must be array');invariant(Array.isArray(p.multicamGroups),'multicamGroups must be array');
 const raw=input as Record<string,unknown>;const assetIds=new Set(p.assets.map(a=>a.id));validateGenerativeExtensions(raw,assetIds);assertNoCredentialFields(input);return structuredClone(p as FlickProjectV2);
}
export function parseAnyProject(input:unknown):FlickProjectV2 {if(typeof input==='object'&&input!==null&&(input as {version?:unknown}).version===1)return migrateV1ToV2(parseProject(input) as FlickProject);return parseProjectV2(input)}
export function serializeProjectV2(project:FlickProjectV2):string {assertNoCredentialFields(project);return JSON.stringify(parseProjectV2(project),null,2)+'\n'}
