import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {LocalProductAnalyzerHttp,buildDeterministicBrandLayers,planDeterministicBrandFinish} from '../src/index.ts';

async function mock(){const s=createServer(async(req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json'});res.end('{"ok":true}');return}let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw||'{}');res.writeHead(200,{'content-type':'application/json'});if(req.url==='/v1/build-identity'){assert.equal(body.references.length,2);res.end(JSON.stringify({expectedOcrStrings:['Sprite','Zero Sugar'],silhouetteReferenceAssetId:'front',protectedColors:[{name:'sprite-green',referenceLab:[80,-60,40],maxDeltaE:5}],features:{ocr:'fixture'}}));return}if(req.url==='/v1/analyze-product'){assert.equal(body.identity.name,'Sprite Zero Sugar');res.end(JSON.stringify({observedOcrStrings:['Sprite','Zero Sugar'],measurements:{ocrSimilarity:1,logoSimilarity:.99,silhouetteSimilarity:.98,colorSimilarity:.97,segmentationStability:.95,temporalConsistency:.93,flickerScore:.04,cameraAdherence:.9,productOccupancy:.5}}));return}res.end('{}')});await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const a=s.address() as any;return{url:`http://127.0.0.1:${a.port}`,close:()=>new Promise<void>(r=>s.close(()=>r()))}}

test('localhost analyzer builds identity and measures candidates without cloud dependencies',async()=>{const m=await mock();try{const a=new LocalProductAnalyzerHttp({baseUrl:m.url,resolveAsset:async id=>({bytes:Buffer.from(id),mediaType:'image/png'})});const identity=await a.buildIdentity('sprite','Sprite Zero Sugar',['front','side']);assert.deepEqual(identity.expectedOcrStrings,['Sprite','Zero Sugar']);assert.equal(identity.silhouetteReferenceAssetId,'front');const measurements=await a.analyze(identity,'candidate');assert.equal(measurements.ocrSimilarity,1);assert.equal(measurements.flickerScore,.04)}finally{await m.close()}});

test('brand finish compiles exact text and logo instructions into locked native V3 layers',()=>{const identity={id:'x',name:'Product',approvedAssetIds:['front'],expectedOcrStrings:['EXACT COPY'],logoReferenceAssetIds:['logo'],protectedRegionAssetIds:['label']};const plan=planDeterministicBrandFinish(identity,'plate');const placements=Object.fromEntries(plan.instructions.map((x,i)=>[x.id,{position:[100+i*50,100,0] as const,fontSize:48}]));const layers=buildDeterministicBrandLayers(plan,90,placements);assert.equal(layers.length,3);assert.ok(layers.every(l=>l.locked&&l.props?.generatedByModel===false));assert.ok(layers.some(l=>l.kind==='text'&&l.text==='EXACT COPY'));assert.ok(layers.some(l=>l.kind==='image'&&l.assetId==='logo'))});
