import test from 'node:test';
import assert from 'node:assert/strict';
import { migrateV2ToV3, parseProjectV3, type FlickProjectV2 } from '../src/index.ts';

function base(){const v2:FlickProjectV2={version:2,id:'p',name:'P',format:{width:1920,height:1080,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[{id:'source',path:'/tmp/source.png',kind:'image'},{id:'out',path:'/tmp/out.png',kind:'image'},{id:'depth',path:'/tmp/depth.png',kind:'image'}],rootCompositionId:'root',compositions:[{id:'root',name:'Root',width:1920,height:1080,tracks:[]}],masks:[],audioBuses:[],multicamGroups:[],perception:{providers:[]},preview:{quality:'full',preferGpu:true},markers:[],style:{},provenance:[],checkpoints:[],branches:[]};return migrateV2ToV3(v2)}
const record={id:'g1',kind:'image' as const,provider:'openai',model:'gpt-image-1',prompt:'hero',inputAssetIds:['source'],outputAssetIds:['out'],parameters:{quality:'high'},requestHash:'abc',usage:{units:1,costUsd:.04},rights:{commercialAllowed:true,attributionRequired:false},createdAt:'2026-10-09T00:00:00Z'};
const scene={id:'s1',sourceAssetId:'source',layerAssetIds:['out'],depthAssetId:'depth',decompositionProvider:'fixture',layers:[{id:'layer',assetId:'out',name:'Hero',z:2,bounds:{x:0,y:0,width:100,height:100},confidence:.9,depthRange:[.2,.8] as const}],diagnostics:[]};

test('generation records and layered scenes round-trip through v3 validation',()=>{const p=parseProjectV3({...base(),generationRecords:[record],generatedScenes:[scene]});assert.equal(p.generationRecords?.[0].id,'g1');assert.equal(p.generatedScenes?.[0].layers[0].z,2)});
test('generation validation rejects duplicate ids, unknown assets, credentials and non-finite values',()=>{assert.throws(()=>parseProjectV3({...base(),generationRecords:[record,{...record}]}),/duplicate.*generation/i);assert.throws(()=>parseProjectV3({...base(),generationRecords:[{...record,outputAssetIds:['missing']}]}),/asset/i);assert.throws(()=>parseProjectV3({...base(),generationRecords:[{...record,parameters:{apiKey:'secret'}}]}),/credential|secret|apiKey/i);assert.throws(()=>parseProjectV3({...base(),generationRecords:[{...record,usage:{costUsd:Number.NaN}}]}),/finite/i);assert.throws(()=>parseProjectV3({...base(),generatedScenes:[{...scene,cleanPlateAssetId:'missing'}]}),/asset/i);assert.throws(()=>parseProjectV3({...base(),generatedScenes:[{...scene,layers:[{...scene.layers[0],z:Number.POSITIVE_INFINITY}]}]}),/finite/i)});
