import type {GenerationRequest} from '../../generation/src/types.ts';
import {clampCandidateCount,type LocalHardwareProfile} from '../../generation/src/hardware.ts';
import {planAnchorFrames,type AnchorPlanRequest} from './anchors.ts';

export interface LocalAnchorWorkflowRequest{projectId:string;sourceAssetId:string;referenceAssetIds?:string[];prompt:string;durationFrames:number;sceneStartFrames?:number[];targetSpacingFrames?:number;maxAnchors?:number;hardwareProfile:LocalHardwareProfile;imageWidth?:number;imageHeight?:number}
export interface LocalAnchorWorkflowPlan{anchorFrames:number[];anchorRequests:GenerationRequest[];diagnostics:string[]}
export interface LocalInterpolationRequest{projectId:string;requestId:string;prompt:string;firstAnchorAssetId:string;lastAnchorAssetId?:string;referenceAssetIds?:string[];durationSeconds:number;resolution?:string;aspectRatio?:string;camera?:Record<string,unknown>;motionMaskAssetIds?:string[];hardwareProfile:LocalHardwareProfile;candidateCount?:number;seed?:number|string}

export function buildLocalAnchorWorkflow(input:LocalAnchorWorkflowRequest):LocalAnchorWorkflowPlan{const plan=planAnchorFrames({durationFrames:input.durationFrames,sceneStartFrames:input.sceneStartFrames,targetSpacingFrames:input.targetSpacingFrames,maxAnchors:input.maxAnchors} satisfies AnchorPlanRequest),candidateCount=clampCandidateCount(input.hardwareProfile),refs=input.referenceAssetIds??[],anchorRequests=plan.frames.filter(frame=>frame!==0).map((frame,index):GenerationRequest=>({id:`anchor_${String(index+1).padStart(3,'0')}_f${frame}`,projectId:input.projectId,kind:'image-edit',prompt:`${input.prompt}\nCreate a high-fidelity anchor for frame ${frame} of ${input.durationFrames-1}. Preserve product identity, geometry, approved logos and packaging regions. Do not invent replacement brand typography.`,inputAssetIds:[input.sourceAssetId,...refs],parameters:{candidateCount,width:input.imageWidth,height:input.imageHeight,anchorFrame:frame,totalFrames:input.durationFrames},provider:undefined}));return{anchorFrames:plan.frames,anchorRequests,diagnostics:plan.diagnostics}}

export function buildLocalInterpolationRequest(input:LocalInterpolationRequest):GenerationRequest{if(input.durationSeconds<=0||!Number.isFinite(input.durationSeconds))throw new Error('Interpolation duration must be positive');const candidateCount=clampCandidateCount(input.hardwareProfile,input.candidateCount);return{id:input.requestId,projectId:input.projectId,kind:'video',prompt:input.prompt,inputAssetIds:[input.firstAnchorAssetId],parameters:{pipeline:'anchor-interpolation'},video:{firstFrameAssetId:input.firstAnchorAssetId,lastFrameAssetId:input.lastAnchorAssetId,referenceAssetIds:input.referenceAssetIds??[],durationSeconds:input.durationSeconds,resolution:input.resolution,aspectRatio:input.aspectRatio,camera:input.camera,motionMaskAssetIds:input.motionMaskAssetIds??[],candidateCount},seed:input.seed}}
