import type { LayeredImageScene } from '../../schema/src/v3/project.ts';
import type { GenerationRequest,GenerationRequirements } from '../../generation/src/types.ts';
import type { OcclusionAssessment,PlannedSceneMotion } from './types.ts';
function clamp(v:number){return Math.max(0,Math.min(1,v))}
export function assessOcclusionRisk(scene:LayeredImageScene,motion:PlannedSceneMotion):OcclusionAssessment{const result:OcclusionAssessment={needsCleanPlate:false,revealRiskByLayer:{},requiredInpaintMaskAssetIds:[],diagnostics:[]};const cameraMagnitude=Math.hypot(motion.camera.dx,motion.camera.dy)+Math.abs(motion.camera.pushIn)*100;for(const layer of scene.layers){const m=motion.layers[layer.id]??{dx:0,dy:0},relative=Math.hypot(m.dx-motion.camera.dx,m.dy-motion.camera.dy)+cameraMagnitude*.25;const scale=Math.max(1,Math.min(layer.bounds.width,layer.bounds.height)),risk=clamp(relative/scale*2);result.revealRiskByLayer[layer.id]=risk;if(risk>.04&&layer.z>=0){result.needsCleanPlate=true;const mask=layer.maskAssetId;if(typeof mask==='string'&&mask.trim())result.requiredInpaintMaskAssetIds.push(mask);result.diagnostics.push(`layer ${layer.id} may reveal ${Math.round(risk*100)}% unsupported background coverage`)}}result.requiredInpaintMaskAssetIds=[...new Set(result.requiredInpaintMaskAssetIds)];const hasPlate=Boolean(scene.cleanPlateAssetId||(scene.cleanPlateAssetIds?.length??0)>0);if(result.needsCleanPlate&&!hasPlate){result.diagnostics.push('clean plate required before applying the planned relative motion');if(!result.requiredInpaintMaskAssetIds.length)result.diagnostics.push('no accepted inpaint mask is available for the required clean-plate repair')}return result}

const CLEAN_PLATE_PROMPT='Reconstruct only the background hidden by the supplied foreground mask. Preserve perspective, lighting, texture, and scene geometry. Do not add text, logos, people, or new objects.';
export function buildCleanPlateGenerationRequests(projectId:string,scene:LayeredImageScene,assessment:OcclusionAssessment):GenerationRequest[]{if(!projectId.trim())throw new Error('projectId is required for clean-plate generation');if(!assessment.needsCleanPlate)return[];return[...new Set(assessment.requiredInpaintMaskAssetIds)].map((maskAssetId,index)=>({id:`cleanplate:${scene.id}:${index+1}`,projectId,kind:'inpaint',prompt:CLEAN_PLATE_PROMPT,inputAssetIds:[scene.sourceAssetId,maskAssetId],parameters:{sceneId:scene.id,maskAssetId,purpose:'clean-plate',preserveSourceGeometry:true}}))}
export interface CleanPlateGenerationRuntime{submit(request:GenerationRequest,requirements?:GenerationRequirements):string}
export function submitCleanPlateRepairs(runtime:CleanPlateGenerationRuntime,projectId:string,scene:LayeredImageScene,assessment:OcclusionAssessment):{jobIds:string[];requests:GenerationRequest[]}{const requests=buildCleanPlateGenerationRequests(projectId,scene,assessment);if(assessment.needsCleanPlate&&!requests.length)throw new Error('Clean-plate repair is required but no inpaint masks are available');const requirements:GenerationRequirements={supportsMasks:true,supportsReferences:true};return{requests,jobIds:requests.map(request=>runtime.submit(request,requirements))}}
export function withCleanPlateAssets(scene:LayeredImageScene,assetIds:string[]):LayeredImageScene{const ids=[...new Set(assetIds.filter(id=>typeof id==='string'&&id.trim()).map(id=>id.trim()))];if(!ids.length)throw new Error('At least one accepted clean-plate asset is required');return{...structuredClone(scene),cleanPlateAssetId:ids[0],cleanPlateAssetIds:ids,diagnostics:[...scene.diagnostics]}}
