import {LOCAL_HARDWARE_PROFILES,type LocalHardwareProfile} from '../../generation/src/hardware.ts';
import type {GenerationRequirements} from '../../generation/src/types.ts';

export type LocalShotStrategy='deterministic-2d'|'layered-2.5d'|'local-video'|'blocked';
export type ShotMotionKind='static'|'reframe'|'graphics'|'push'|'pan'|'orbit'|'fluid'|'object-motion'|'lighting-change';
export interface ShotMotionIntent{id:string;kind:ShotMotionKind;cameraRotationDegrees?:number;hiddenSurfaceReveal?:boolean;fluidMotion?:boolean;deformingMotion?:boolean;changingReflections?:boolean;referenceImageCount?:number;requiresExactProductGeometry?:boolean;durationSeconds?:number;resolution?:string;aspectRatio?:string;useLastFrameAnchor?:boolean;useMotionMask?:boolean}
export interface ShotRouteDecision{strategy:LocalShotStrategy;reason:string;diagnostics:string[];requirements?:GenerationRequirements;minimumReferenceImages?:number}

export function routeLocalShot(intent:ShotMotionIntent,profile:LocalHardwareProfile):ShotRouteDecision{const refs=Math.max(0,Math.floor(intent.referenceImageCount??1)),rot=Math.abs(intent.cameraRotationDegrees??0),complex=Boolean(intent.hiddenSurfaceReveal||intent.fluidMotion||intent.deformingMotion||intent.changingReflections||intent.kind==='fluid'||intent.kind==='object-motion'||intent.kind==='lighting-change'||(intent.kind==='orbit'&&rot>10));if(intent.requiresExactProductGeometry&&intent.hiddenSurfaceReveal&&refs<2)return{strategy:'blocked',reason:'Exact hidden product surfaces cannot be recovered faithfully from a single reference image',diagnostics:['Add at least one additional approved product viewpoint or use a reconstructed 3D product asset'],minimumReferenceImages:2};if(intent.kind==='static'||intent.kind==='reframe'||intent.kind==='graphics')return{strategy:'deterministic-2d',reason:'The shot does not require novel pixels or hidden geometry',diagnostics:[]};if(!complex&&(intent.kind==='push'||intent.kind==='pan'||(intent.kind==='orbit'&&rot<=10)))return{strategy:'layered-2.5d',reason:'Requested motion stays within restrained parallax and should remain deterministic/editable',diagnostics:rot>7?['Orbit-like motion is near the 2.5D safety limit; inspect revealed edges']:[]};const hardware=LOCAL_HARDWARE_PROFILES[profile];if(!hardware.localVideo)return{strategy:'blocked',reason:`${profile} profile cannot synthesize the novel pixels this shot requires`,diagnostics:['Use a GPU local worker, reduce the motion, or provide more real coverage; do not silently substitute fake parallax']};const requirements:GenerationRequirements={execution:'local',supportsReferences:refs>0,video:{firstFrame:true,lastFrame:intent.useLastFrameAnchor===true,referenceImages:Math.max(0,refs-1),durationSeconds:intent.durationSeconds,resolution:intent.resolution,aspectRatio:intent.aspectRatio,cameraControl:intent.kind==='orbit'||rot>0,motionMasks:intent.useMotionMask===true||intent.fluidMotion===true}};return{strategy:'local-video',reason:'The shot requires temporal synthesis or novel view/material behavior',diagnostics:[`Route to a free local I2V worker under the ${profile} hardware profile`],requirements}}
