import { createHash } from 'node:crypto';
import { copyFileSync,existsSync,mkdirSync,readFileSync } from 'node:fs';
import { join,resolve } from 'node:path';
import { assertNoCredentialFields } from '../../schema/src/secrets.ts';
import type { Asset } from '../../schema/src/project.ts';
import type { GenerationRecord } from '../../schema/src/v3/project.ts';
import type { GenerationRequest,StagedGenerationOutput } from './types.ts';
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object'){const o=value as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+stable(o[k])).join(',')}}`}return JSON.stringify(value)}
function ext(mediaType:string):string{return{'image/png':'.png','image/webp':'.webp','image/jpeg':'.jpg','video/mp4':'.mp4','audio/wav':'.wav','audio/mpeg':'.mp3'}[mediaType]??'.bin'}
function kind(mediaType:string):Asset['kind']{if(mediaType.startsWith('video/'))return'video';if(mediaType.startsWith('audio/'))return'audio';return'image'}
export function buildGenerationAcceptance(request:GenerationRequest,staged:StagedGenerationOutput,assetRoot:string):{assets:Asset[];record:GenerationRecord}{assertNoCredentialFields(request,'generationRequest');const root=resolve(assetRoot);mkdirSync(root,{recursive:true});const assets:Asset[]=staged.outputs.map(o=>{const bytes=readFileSync(o.path),hash=createHash('sha256').update(bytes).digest('hex');if(o.sha256&&o.sha256!==hash)throw new Error(`Staged generation hash mismatch for ${o.path}`);const id=`gen_${hash.slice(0,24)}`,path=join(root,`${hash}${ext(o.mediaType)}`);if(!existsSync(path))copyFileSync(o.path,path);return{id,path,kind:kind(o.mediaType),metadata:{sha256:hash,mediaType:o.mediaType,generated:true,provider:staged.provider,model:staged.model,generationRequestId:request.id}}});const requestHash=createHash('sha256').update(stable(request)).digest('hex');const record:GenerationRecord={id:request.id,kind:request.kind,provider:staged.provider,model:staged.model,prompt:request.prompt,inputAssetIds:[...request.inputAssetIds],outputAssetIds:assets.map(a=>a.id),parameters:structuredClone(request.parameters),seed:request.seed,requestHash,usage:staged.usage?structuredClone(staged.usage):undefined,rights:staged.rights?structuredClone(staged.rights):undefined,createdAt:staged.createdAt??new Date().toISOString()};for(const key of Object.keys(record) as Array<keyof GenerationRecord>)if(record[key]===undefined)delete (record as any)[key];return{assets,record}}
