import type {GenerationRequest,StagedGenerationOutput} from './types.ts';
import {buildGenerationAcceptance} from './accept.ts';
import {evaluateProductFidelity,type ProductCandidateMeasurements,type ProductIdentityPackage,type ProductFidelityReport} from '../../product-fidelity/src/index.ts';
import {evaluateGenerationQC,type GenerationQCConfig,type GenerationQCMetrics,type GenerationQCReport} from '../../generation-qc/src/index.ts';

export interface GenerationCandidateReview{outputIndex:number;measurements:ProductCandidateMeasurements;generationMetrics?:GenerationQCMetrics;aestheticScore?:number;promptAdherence?:number}
export interface RankedGenerationCandidate{outputIndex:number;approved:boolean;score:number;fidelity:ProductFidelityReport;generation:GenerationQCReport;aestheticScore:number;promptAdherence:number;reasons:string[]}
export interface CandidateRankingOptions{generationQC?:GenerationQCConfig;minAestheticScore?:number;minPromptAdherence?:number;brandWeight?:number;generationWeight?:number;aestheticWeight?:number;promptWeight?:number}
const clamp=(n:number)=>Math.max(0,Math.min(1,Number.isFinite(n)?n:0));

export function rankGenerationCandidates(identity:ProductIdentityPackage,reviews:GenerationCandidateReview[],options:CandidateRankingOptions={}):RankedGenerationCandidate[]{const brandWeight=options.brandWeight??.5,generationWeight=options.generationWeight??.3,aestheticWeight=options.aestheticWeight??.1,promptWeight=options.promptWeight??.1,total=Math.max(1e-9,brandWeight+generationWeight+aestheticWeight+promptWeight);return reviews.map(review=>{const promptAdherence=clamp(review.promptAdherence??review.measurements.promptAdherence??1),aestheticScore=clamp(review.aestheticScore??review.measurements.aestheticScore??.5),fidelity=evaluateProductFidelity(identity,review.measurements),generation=evaluateGenerationQC({...((review.generationMetrics)??{}),segmentationStability:review.generationMetrics?.segmentationStability??review.measurements.segmentationStability,temporalConsistency:review.generationMetrics?.temporalConsistency??review.measurements.temporalConsistency,flickerScore:review.generationMetrics?.flickerScore??review.measurements.flickerScore,cameraAdherence:review.generationMetrics?.cameraAdherence??review.measurements.cameraAdherence,productOccupancy:review.generationMetrics?.productOccupancy??review.measurements.productOccupancy,promptAdherence:review.generationMetrics?.promptAdherence??promptAdherence},options.generationQC),reasons=[...fidelity.issues.map(i=>i.message),...generation.issues.map(i=>i.message)];if(aestheticScore<(options.minAestheticScore??.35))reasons.push(`Aesthetic score ${aestheticScore.toFixed(3)} is below ${(options.minAestheticScore??.35).toFixed(3)}`);if(promptAdherence<(options.minPromptAdherence??.6))reasons.push(`Prompt adherence ${promptAdherence.toFixed(3)} is below ${(options.minPromptAdherence??.6).toFixed(3)}`);const approved=fidelity.approved&&generation.approved&&aestheticScore>=(options.minAestheticScore??.35)&&promptAdherence>=(options.minPromptAdherence??.6),score=(fidelity.score*brandWeight+generation.score*generationWeight+aestheticScore*aestheticWeight+promptAdherence*promptWeight)/total;return{outputIndex:review.outputIndex,approved,score,fidelity,generation,aestheticScore,promptAdherence,reasons}}).sort((a,b)=>Number(b.approved)-Number(a.approved)||b.score-a.score||a.outputIndex-b.outputIndex)}

export function acceptRankedGenerationCandidates(request:GenerationRequest,staged:StagedGenerationOutput,identity:ProductIdentityPackage,reviews:GenerationCandidateReview[],assetRoot:string,options:CandidateRankingOptions&{maxAccepted?:number}={}):{ranking:RankedGenerationCandidate[];acceptance:ReturnType<typeof buildGenerationAcceptance>}{const ranking=rankGenerationCandidates(identity,reviews,options),limit=Math.max(1,Math.floor(options.maxAccepted??1)),selected=ranking.filter(r=>r.approved).slice(0,limit);if(!selected.length)throw new Error(`No generated candidate passed product/generation QC: ${ranking.flatMap(r=>r.reasons).slice(0,6).join('; ')}`);const outputs=selected.map(r=>{const out=staged.outputs[r.outputIndex];if(!out)throw new Error(`Candidate output index ${r.outputIndex} is out of range`);return out}),filtered:StagedGenerationOutput={...staged,outputs,providerMetadata:{...(staged.providerMetadata??{}),candidateRanking:ranking.map(r=>({outputIndex:r.outputIndex,approved:r.approved,score:r.score})),acceptedOriginalOutputIndices:selected.map(r=>r.outputIndex)}};return{ranking,acceptance:buildGenerationAcceptance(request,filtered,assetRoot)}}
