import { assertNoCredentialFields } from '../../schema/src/secrets.ts';
import type { Job } from '../../jobs/src/types.ts';
import { JobScheduler } from '../../jobs/src/scheduler.ts';
import { GenerationProviderRegistry } from './registry.ts';
import { removeStagedOutput,stageProviderOutput } from './staging.ts';
import type { GenerationRequest,GenerationRequirements,ProviderCapabilityManifest,StagedGenerationOutput } from './types.ts';
const JOB_TYPE='generation.execute';
function sanitize(message:string):string{return message.replace(/sk-[A-Za-z0-9_-]+/g,'[redacted]').replace(/(api[_-]?key|token|password|secret)\s*[:=]\s*\S+/gi,'$1=[redacted]')}
export class GenerationRuntime{readonly registry:GenerationProviderRegistry;readonly scheduler:JobScheduler;readonly stagingRoot:string;#staged=new Map<string,StagedGenerationOutput>();#requests=new Map<string,GenerationRequest>();constructor(options:{registry:GenerationProviderRegistry;scheduler:JobScheduler;stagingRoot:string}){this.registry=options.registry;this.scheduler=options.scheduler;this.stagingRoot=options.stagingRoot;this.scheduler.register(JOB_TYPE,async(job,signal)=>{const payload=job.payload as {request:GenerationRequest;provider:string};const request=structuredClone(payload.request);try{const provider=this.registry.resolve({...request,provider:payload.provider});const raw=await provider.generate(request,signal);if(signal.aborted)throw new Error('generation cancelled');const staged=stageProviderOutput(raw,this.stagingRoot,job.id);if(signal.aborted){removeStagedOutput(staged,this.stagingRoot);throw new Error('generation cancelled')}this.#staged.set(job.id,staged);return{provider:staged.provider,model:staged.model,outputCount:staged.outputs.length,hashes:staged.outputs.map(o=>o.sha256)}}catch(e){const msg=e instanceof Error?e.message:String(e);throw new Error(sanitize(msg))}})}listProviders():ProviderCapabilityManifest[]{return this.registry.list()}submit(request:GenerationRequest,requirements:GenerationRequirements={}):string{assertNoCredentialFields(request,'generationRequest');if(!request.id.trim()||!request.projectId.trim())throw new Error('generation request id and projectId are required');const provider=this.registry.resolve(request,requirements),providerId=provider.manifest().provider;const job=this.scheduler.store.enqueue({projectId:request.projectId,type:JOB_TYPE,resourceClass:'model',payload:{request:structuredClone(request),provider:providerId},idempotencyKey:`generation:${request.id}`,dependencies:[],retryClass:'manual'});this.#requests.set(job.id,structuredClone(request));return job.id}status(jobId:string):Job|undefined{return this.scheduler.store.get(jobId)}request(jobId:string):GenerationRequest|undefined{const r=this.#requests.get(jobId);return r?structuredClone(r):undefined}staged(jobId:string):StagedGenerationOutput|undefined{const job=this.status(jobId);if(job?.state!=='completed')return undefined;const s=this.#staged.get(jobId);return s?structuredClone(s):undefined}cancel(jobId:string):boolean{const cancelled=this.scheduler.cancel(jobId);if(cancelled){removeStagedOutput(this.#staged.get(jobId),this.stagingRoot);this.#staged.delete(jobId)}return cancelled}discard(jobId:string):void{removeStagedOutput(this.#staged.get(jobId),this.stagingRoot);this.#staged.delete(jobId)}}
