import test from 'node:test';import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';import { tmpdir } from 'node:os';import { join } from 'node:path';import { spawnSync } from 'node:child_process';
import type { FlickProjectV2, V2Clip } from '../../packages/schema/src/index.ts';import { renderProjectV2 } from '../../packages/render-ffmpeg/src/index.ts';import { materializeMulticamProgram } from '../../packages/multicam/src/index.ts';
function run(args:string[]){const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8'});if(r.status!==0)throw new Error(r.stderr);}
function color(path:string,c:string,d=1,audio=false){const args=['-f','lavfi','-i',`color=c=${c}:s=64x64:r=30:d=${d}`];if(audio)args.push('-f','lavfi','-i',`sine=frequency=440:sample_rate=48000:duration=${d}`,'-c:a','aac','-shortest');args.push('-c:v','libx264','-pix_fmt','yuv420p',path);run(args);}
function audio(path:string,f:number,vol:number){run(['-f','lavfi','-i',`sine=frequency=${f}:sample_rate=48000:duration=1`,'-af',`volume=${vol}`,'-c:a','pcm_s16le',path]);}
function rampSource(path:string){run(['-f','lavfi','-i','color=c=red:s=64x64:r=30:d=0.5','-f','lavfi','-i','color=c=green:s=64x64:r=30:d=0.5','-f','lavfi','-i','color=c=blue:s=64x64:r=30:d=0.5','-filter_complex','[0:v][1:v][2:v]concat=n=3:v=1:a=0[v]','-map','[v]','-c:v','libx264','-pix_fmt','yuv420p',path]);}
function px(path:string,t:number,x=10,y=10){const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-ss',String(t),'-i',path,'-vf',`format=rgb24,crop=1:1:${x}:${y}`,'-frames:v','1','-f','rawvideo','pipe:1'],{encoding:null,maxBuffer:1024*1024});if(r.status!==0)throw new Error(String(r.stderr));return [...(r.stdout as Buffer).subarray(0,3)];}
function meanMusicDb(path:string){const r=spawnSync('ffmpeg',['-hide_banner','-i',path,'-af','highpass=f=150,lowpass=f=300,volumedetect','-f','null','-'],{encoding:'utf8'});const m=(r.stderr||'').match(/mean_volume:\s*(-?[\d.]+) dB/);if(!m)throw new Error('mean volume missing');return Number(m[1]);}
function vc(id:string,assetId:string,duration=30):V2Clip{return{id,assetId,start:0,duration,sourceIn:0,transform:{x:0,y:0,scaleX:1,scaleY:1,rotation:0},opacity:1,blendMode:'normal',maskRefs:[],effectStack:[],enabled:true};}
function project(src:string):FlickProjectV2{return{version:2,id:'p',name:'P',format:{width:64,height:64,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[{id:'src',path:src,kind:'video'}],rootCompositionId:'root',compositions:[{id:'root',name:'Main',width:64,height:64,tracks:[{id:'v',kind:'video',name:'V',clips:[vc('c','src')]}]}],audioBuses:[{id:'master',name:'Master',effects:[],gainDb:0,pan:0}],multicamGroups:[],perception:{providers:[]},preview:{quality:'full',preferGpu:true},markers:[],style:{},provenance:[],checkpoints:[],branches:[]};}

test('linear speed ramp maps output time nonlinearly instead of using average speed',()=>{const d=mkdtempSync(join(tmpdir(),'fsramp-'));try{const src=join(d,'src.mp4'),out=join(d,'out.mp4');rampSource(src);const p=project(src);p.compositions[0].tracks[0].clips[0].speedCurve={points:[{frame:0,speed:.5},{frame:30,speed:2}]};renderProjectV2(p,out);const mid=px(out,.5),late=px(out,.93);assert.ok(mid[0]>150&&mid[1]<100,`mid must still be red: ${mid}`);assert.ok(late[2]>120,`late must reach blue: ${late}`);}finally{rmSync(d,{recursive:true,force:true});}});

test('rectangle mask actually limits rendered overlay pixels',()=>{const d=mkdtempSync(join(tmpdir(),'fsmask-'));try{const r=join(d,'r.mp4'),b=join(d,'b.mp4'),out=join(d,'o.mp4');color(r,'red');color(b,'blue');const p=project(r);p.assets.push({id:'b',path:b,kind:'video'});p.compositions[0].tracks.push({id:'top',kind:'video',name:'Top',zIndex:1,clips:[vc('b','b')]});p.masks=[{id:'left',kind:'rect',x:0,y:0,width:32,height:64,feather:0,invert:false}];p.compositions[0].tracks[1].clips[0].maskRefs=['left'];renderProjectV2(p,out);const left=px(out,.5,10,20),right=px(out,.5,50,20);assert.ok(left[2]>150,`left blue ${left}`);assert.ok(right[0]>150&&right[2]<100,`right red ${right}`);}finally{rmSync(d,{recursive:true,force:true});}});

test('sidechain ducking lowers music bus while dialogue is active',()=>{const d=mkdtempSync(join(tmpdir(),'fsduck-'));try{const video=join(d,'v.mp4'),dialogue=join(d,'d.wav'),music=join(d,'m.wav'),dry=join(d,'dry.mp4'),duck=join(d,'duck.mp4');color(video,'black');audio(dialogue,440,.5);audio(music,220,.5);const p=project(video);p.assets.push({id:'d',path:dialogue,kind:'audio'},{id:'m',path:music,kind:'audio'});p.compositions[0].tracks.push({id:'d',kind:'audio',name:'D',clips:[{...vc('dc','d'),busId:'dialogue'}]},{id:'m',kind:'audio',name:'M',clips:[{...vc('mc','m'),busId:'music'}]});p.audioBuses=[{id:'master',name:'Master',effects:[],gainDb:0,pan:0},{id:'dialogue',name:'Dialogue',effects:[],gainDb:0,pan:0,outputBusId:'master'},{id:'music',name:'Music',effects:[],gainDb:0,pan:0,outputBusId:'master'}];renderProjectV2(p,dry);p.audioBuses[2].effects=[{id:'duck',type:'ducking',enabled:true,params:{sidechainBusId:'dialogue',thresholdDb:-35,ratio:12,attackMs:5,releaseMs:80}}];renderProjectV2(p,duck);assert.ok(meanMusicDb(duck)<meanMusicDb(dry)-2,`dry music ${meanMusicDb(dry)} ducked music ${meanMusicDb(duck)}`);}finally{rmSync(d,{recursive:true,force:true});}});

test('multicam program materializes angle choices into renderable timeline clips',()=>{const p=project('/tmp/a.mp4');p.assets=[{id:'a',path:'/tmp/a.mp4',kind:'video'},{id:'b',path:'/tmp/b.mp4',kind:'video'}];p.multicamGroups=[{id:'mc',name:'Interview',angles:[{id:'A',assetId:'a',sourceOffset:10,confidence:1},{id:'B',assetId:'b',sourceOffset:20,confidence:1}],program:[{start:0,end:30,angleId:'A'},{start:30,end:60,angleId:'B'}]}];const q=materializeMulticamProgram(p,'mc','root','program');const t=q.compositions[0].tracks.find(x=>x.id==='program')!;assert.deepEqual(t.clips.map(c=>[c.assetId,c.start,c.duration,c.sourceIn]),[['a',0,30,10],['b',30,30,50]]);});
