import type {AnimatedProperty,MotionInterpolation,MotionKeyframe,Vec3} from '../../../../packages/schema/src/v3/project.ts';
import type {CurveHandle} from '../../../../packages/schema/src/v2/project.ts';
import {evaluateAnimatedNumber,sampleVelocity} from '../../../../packages/animation/src/index.ts';
export interface CurveViewport{frameMin:number;frameMax:number;valueMin:number;valueMax:number;width:number;height:number}
export type GraphViewport=CurveViewport;
export interface GraphPoint{frame:number;value:number}
export interface SpeedInfluence{speed:number;influence:number}
const finite=(n:number,name:string)=>{if(!Number.isFinite(n))throw new Error(`${name} must be finite`);return n};
export function graphToScreen(p:GraphPoint,v:CurveViewport):{x:number;y:number}{const fw=v.frameMax-v.frameMin,vh=v.valueMax-v.valueMin;if(fw<=0||vh<=0||v.width<=0||v.height<=0)throw new Error('Invalid curve viewport');return{x:(p.frame-v.frameMin)/fw*v.width,y:v.height-(p.value-v.valueMin)/vh*v.height};}
export function screenToGraph(p:{x:number;y:number},v:CurveViewport):GraphPoint{if(v.width<=0||v.height<=0)throw new Error('Invalid curve viewport');return{frame:v.frameMin+p.x/v.width*(v.frameMax-v.frameMin),value:v.valueMin+(v.height-p.y)/v.height*(v.valueMax-v.valueMin)}}
export function segmentControlPoints(a:MotionKeyframe<number>,b:MotionKeyframe<number>){const dt=b.frame-a.frame,dv=b.value-a.value,out=a.outTangent??{x:1/3,y:1/3},incoming=b.inTangent??{x:2/3,y:2/3};return{p0:{frame:a.frame,value:a.value},p1:{frame:a.frame+dt*out.x,value:a.value+dv*out.y},p2:{frame:a.frame+dt*incoming.x,value:a.value+dv*incoming.y},p3:{frame:b.frame,value:b.value}};}
export function handleToSpeedInfluence(h:CurveHandle,side:'out'|'in',frameA:number,frameB:number,valueA:number,valueB:number):SpeedInfluence{const dt=frameB-frameA,dv=valueB-valueA;if(dt<=0)throw new Error('Keyframes must be ordered');if(side==='out'){const dx=Math.max(1e-9,h.x);return{speed:(h.y*dv)/(dx*dt),influence:h.x*100};}const dx=Math.max(1e-9,1-h.x);return{speed:((1-h.y)*dv)/(dx*dt),influence:(1-h.x)*100};}
export function speedInfluenceToHandle(v:SpeedInfluence,side:'out'|'in',frameA:number,frameB:number,valueA:number,valueB:number):CurveHandle{finite(v.speed,'speed');const dt=frameB-frameA,dv=valueB-valueA;if(dt<=0)throw new Error('Keyframes must be ordered');const inf=Math.max(0.0001,Math.min(100,v.influence))/100;if(Math.abs(dv)<1e-12)return side==='out'?{x:inf,y:0}:{x:1-inf,y:1};const dy=v.speed*(inf*dt)/dv;return side==='out'?{x:inf,y:dy}:{x:1-inf,y:1-dy};}
export interface CurveShapeKey{interpolation:MotionInterpolation;inTangent?:CurveHandle;outTangent?:CurveHandle}
export function copyCurveShape<T>(keys:MotionKeyframe<T>[]):CurveShapeKey[]{return keys.map(k=>({interpolation:k.interpolation,inTangent:k.inTangent?{...k.inTangent}:undefined,outTangent:k.outTangent?{...k.outTangent}:undefined}));}
export function pasteCurveShape<T>(keys:MotionKeyframe<T>[],shape:CurveShapeKey[]):MotionKeyframe<T>[]{if(shape.length!==keys.length)throw new Error('Curve shape/keyframe count mismatch');return keys.map((k,i)=>({...structuredClone(k),...structuredClone(shape[i])}));}
export function mirrorHandle(h:CurveHandle):CurveHandle{return{x:1-h.x,y:1-h.y}}
export function setKeyframeHandle<T>(key:MotionKeyframe<T>,side:'in'|'out',handle:CurveHandle,linked=false):MotionKeyframe<T>{const next=structuredClone(key);if(side==='in'){next.inTangent={...handle};if(linked)next.outTangent=mirrorHandle(handle);}else{next.outTangent={...handle};if(linked)next.inTangent=mirrorHandle(handle);}next.interpolation='bezier';return next;}
export function sampleValueGraph(property:AnimatedProperty<number>,start:number,end:number,count:number):Array<GraphPoint&{speed:number}>{if(count<2)throw new Error('count must be >=2');const out=[];for(let i=0;i<count;i++){const frame=start+(end-start)*(i/(count-1));out.push({frame,value:evaluateAnimatedNumber(property,frame),speed:sampleVelocity(property,frame)});}return out;}
export function spatialPathDots(keys:MotionKeyframe<Vec3>[],samplesPerSegment=8):Array<{frame:number;position:Vec3}>{const ordered=[...keys].sort((a,b)=>a.frame-b.frame),out:Array<{frame:number;position:Vec3}>=[];for(let i=1;i<ordered.length;i++){const a=ordered[i-1],b=ordered[i];for(let s=i===1?0:1;s<=samplesPerSegment;s++){const t=s/samplesPerSegment;out.push({frame:a.frame+(b.frame-a.frame)*t,position:[a.value[0]+(b.value[0]-a.value[0])*t,a.value[1]+(b.value[1]-a.value[1])*t,a.value[2]+(b.value[2]-a.value[2])*t]});}}return out;}
