import{existsSync,mkdirSync,writeFileSync}from'node:fs';import{basename,dirname,join,resolve}from'node:path';import{spawnSync}from'node:child_process';import{generateLocalVideoFromFile,readLocalRuntimeConfig}from'../../packages/local-runtime/src/index.ts';
const args=process.argv.slice(2);const value=(flag:string,fallback?:string)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback};const input=args[0],out=resolve(value('--out','Sprite_Local_Generative_Ad.mp4')!),work=resolve(value('--work',join(dirname(out),'.sprite-local-work'))!),config=readLocalRuntimeConfig(value('--config'));if(!input)throw new Error('Usage: node --experimental-strip-types examples/sprite-local-ad/generate.ts <bottle-image> [--out FILE]');if(!existsSync(input))throw new Error(`Input image not found: ${input}`);mkdirSync(work,{recursive:true});
const prompts=[
'Premium lemon-lime soda commercial, exact same bottle and label geometry as the reference, bottle remains centered and front-facing. Cold condensation beads slowly form and slide on the plastic while tiny carbonation bubbles rise behind it. Dark charcoal studio, narrow emerald rim light, 65 mm lens, extremely restrained slow dolly-in. No new text, no logo changes, no cap changes, no bottle deformation.',
'High-end beverage photography, exact reference bottle stays geometrically unchanged and centered. A crisp burst of clear water, translucent ice fragments, sliced lime and lemon move behind the bottle without covering the label. Fast high-speed-photography motion settles into a clean hero composition. Realistic refraction and droplets, no typography, no label mutation.',
'Extreme cold refreshment shot using the exact reference bottle. Camera makes only a small 5 degree lateral slider move while condensation catches a moving white highlight. Fine mist and carbonation move in the background, bottle silhouette and packaging remain unchanged. Premium 50 mm product cinematography, physically plausible light, no extra words.',
'Final product hero. Exact reference bottle remains front-facing and unchanged on a glossy dark surface. Slow push-in, subtle green backlight blooms, tiny bubbles and mist drift behind it, realistic cold condensation and a clean specular sweep. Minimal premium beverage advertising, no extra objects crossing the label, no text mutations.'
];
const shots:string[]=[];for(let i=0;i<prompts.length;i++){const path=join(work,`shot-${i+1}.mp4`);console.log(`Generating shot ${i+1}/${prompts.length}`);await generateLocalVideoFromFile(config,input,path,{prompt:prompts[i]!,durationSeconds:i===1?3.2:3.0,resolution:'720p',aspectRatio:'16:9',candidateCount:3,seed:740+i*31,strictProductQC:false});shots.push(path)}
const concat=join(work,'concat.txt');writeFileSync(concat,shots.map(p=>`file '${p.replaceAll("'","'\\''")}'`).join('\n')+'\n');const ff=spawnSync('ffmpeg',['-y','-f','concat','-safe','0','-i',concat,'-vf',"fps=30,scale=1920:1080:flags=lanczos,eq=contrast=1.04:saturation=1.05,format=yuv420p",'-an','-c:v','libx264','-preset','slow','-crf','16','-movflags','+faststart',out],{stdio:'inherit'});if(ff.status!==0)throw new Error('ffmpeg final assembly failed');console.log(out);
