import type { FlickProjectV3, MotionComposition, MotionLayer, Rect, Vec3 } from '../../schema/src/v3/project.ts';
import { solveLayout, safeAreaForSurface } from '../../layout/src/index.ts';

export type DesignQCIssueType='text_overflow'|'safe_area'|'small_text'|'contrast'|'collision'|'out_of_bounds'|'clipped_effect'|'alignment'|'spacing'|'small_ui'|'transition_discontinuity'|'camera_velocity'|'short_hold'|'impossible_constraints'|'blank_output'|'static_motion_ratio'|'inactive_shot'|'dead_space'|'readability_projection'|'focal_competition'|'end_card_hold'|'cut_only_energy'|'motion_density'|'single_plane_motion'|'ui_occupancy'|'safe_area_spacing';
export interface DesignQCIssue {id:string;type:DesignQCIssueType;severity:'info'|'warning'|'error';startFrame:number;endFrame:number;message:string;suggestion:string;layerIds?:string[];compositionId:string}
export interface DesignQCResult {issues:DesignQCIssue[];blocking:boolean;compositionId:string}

const pos=(l:MotionLayer):Vec3=>l.transform.position.baseValue;
const scale=(l:MotionLayer):Vec3=>l.transform.scale.baseValue;
function dims(l:MotionLayer):{width:number;height:number}{
  if(l.kind==='text'&&l.textStyle){const box=l.textStyle.paragraphBox;const native=l.props?.nativeTextBounds as Rect|undefined;if(native&&[native.width,native.height].every(Number.isFinite))return{width:native.width,height:native.height};if(box)return{width:box.width,height:box.height};const fs=l.textStyle.fontSize.baseValue;return{width:Math.max(fs,(l.text?.length??1)*fs*.6),height:l.textStyle.lineHeight?.baseValue??fs*1.2};}
  if(l.shape){if(l.shape.kind==='rect')return{width:l.shape.width,height:l.shape.height};if(l.shape.kind==='ellipse')return{width:l.shape.rx*2,height:l.shape.ry*2};if(l.shape.kind==='line')return{width:Math.abs(l.shape.to[0]-l.shape.from[0]),height:Math.abs(l.shape.to[1]-l.shape.from[1])};if(l.shape.kind==='polygon'||l.shape.kind==='path'){const pts=l.shape.kind==='polygon'?l.shape.points:l.shape.points.map(p=>p.point);if(!pts.length)return{width:0,height:0};const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);return{width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)};}if(l.shape.kind==='star')return{width:l.shape.outerRadius*2,height:l.shape.outerRadius*2};}
  const p=l.props??{};return{width:typeof p.width==='number'?p.width:0,height:typeof p.height==='number'?p.height:0};
}
function bounds(l:MotionLayer):Rect {const d=dims(l),p=pos(l),s=scale(l);return{x:p[0],y:p[1],width:Math.abs(d.width*s[0]),height:Math.abs(d.height*s[1])};}
function overlap(a:Rect,b:Rect):boolean{return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;}
function hexRgb(s:string):[number,number,number]|undefined{const m=/^#([0-9a-f]{6})$/i.exec(s);if(!m)return;const n=parseInt(m[1],16);return[(n>>16)&255,(n>>8)&255,n&255];}
function luminance(c:[number,number,number]):number{const f=(v:number)=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)};return .2126*f(c[0])+.7152*f(c[1])+.0722*f(c[2]);}
function contrast(a:string,b:string):number|undefined{const x=hexRgb(a),y=hexRgb(b);if(!x||!y)return;const l1=luminance(x),l2=luminance(y);return(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05);}
function visible(l:MotionLayer):boolean{return l.enabled!==false&&l.opacity.baseValue>0&&!['camera','null','group'].includes(l.kind);}
function norm(v:Vec3):number{return Math.hypot(v[0],v[1],v[2]);}

export function reviewMotionDesign(project:FlickProjectV3,compositionId:string):DesignQCResult {
  const c=project.motionCompositions.find(x=>x.id===compositionId);if(!c)throw new Error(`Unknown motion composition ${compositionId}`);
  const issues:DesignQCIssue[]=[];let seq=0;const push=(type:DesignQCIssueType,severity:DesignQCIssue['severity'],start:number,end:number,message:string,suggestion:string,layerIds?:string[])=>issues.push({id:`dq_${String(++seq).padStart(3,'0')}`,type,severity,startFrame:start,endFrame:end,message,suggestion,layerIds,compositionId:c.id});
  const safe=safeAreaForSurface(c.width,c.height,.05),visuals=c.layers.filter(visible),byBounds=new Map(visuals.map(l=>[l.id,bounds(l)]));
  if(!visuals.length&&c.background==='transparent')push('blank_output','error',0,c.duration,'Motion composition evaluates to a transparent blank frame for its full duration','Add visible content or a non-transparent background');
  for(const l of visuals){const b=byBounds.get(l.id)!;
    if(b.x<0||b.y<0||b.x+b.width>c.width||b.y+b.height>c.height)push('out_of_bounds','warning',l.start,l.start+l.duration,`Layer ${l.id} extends outside composition bounds`,'Move or resize the layer to keep intended content inside the composition',[l.id]);
    if(b.x<safe.x||b.y<safe.y||b.x+b.width>safe.x+safe.width||b.y+b.height>safe.y+safe.height)push('safe_area','warning',l.start,l.start+l.duration,`Layer ${l.id} crosses the title-safe area`,'Reposition important content inside the configured safe area',[l.id]);
    if(l.kind==='text'&&l.textStyle){const fs=l.textStyle.fontSize.baseValue,box=l.textStyle.paragraphBox,native=l.props?.nativeTextBounds as Rect|undefined;if(box){const charCount=[...(l.text??'')].length;const estimatedWidth=charCount*fs*.56+Math.max(0,charCount-1)*(l.textStyle.tracking?.baseValue??0);const estimatedLines=Math.max(1,Math.ceil(estimatedWidth/Math.max(1,box.width)));const estimatedHeight=estimatedLines*(l.textStyle.lineHeight?.baseValue??fs*1.2);const overflow=native?(native.height>box.height+.5||native.width>box.width+.5):estimatedHeight>box.height+.5;if(overflow)push('text_overflow','warning',l.start,l.start+l.duration,`Text in ${l.id} overflows its paragraph box`,'Increase the text box, reduce type size, or shorten the copy; production render bounds use native glyph metrics',[l.id]);}const projected=l.props?.nativeProjectedTextBounds as Rect|undefined;const projectedHeight=projected&&Number.isFinite(projected.height)?projected.height:fs*Math.min(Math.abs(scale(l)[0]),Math.abs(scale(l)[1]));if(projectedHeight<18)push('small_text','warning',l.start,l.start+l.duration,`Text in ${l.id} projects below the 18 px readability threshold`,'Increase font size or projected scale',[l.id]);const fill=typeof l.textStyle.fill?.baseValue==='string'?l.textStyle.fill.baseValue:undefined;if(fill){const ratio=contrast(fill,c.background);if(ratio!==undefined&&ratio<4.5)push('contrast','warning',l.start,l.start+l.duration,`Text/background contrast for ${l.id} is ${ratio.toFixed(2)}:1`,'Use foreground/background colors with at least 4.5:1 contrast for body-sized text',[l.id]);}if((l.props?.role==='title'||l.props?.role==='cta')&&l.duration<30)push('short_hold','warning',l.start,l.start+l.duration,`${l.id} holds for fewer than 30 frames`,'Increase title or CTA hold time so viewers can read it',[l.id]);}
    if(l.props?.uiSurface===true&&(b.width<180||b.height<100))push('small_ui','warning',l.start,l.start+l.duration,`Embedded UI ${l.id} is too small to read reliably`,'Increase the UI close-up or camera scale',[l.id]);
    const effectRadius=Math.max(0,...l.effects.filter(e=>e.enabled).map(e=>typeof e.params.radius==='number'?e.params.radius:0));if(effectRadius>0&&(b.x-effectRadius<0||b.y-effectRadius<0||b.x+b.width+effectRadius>c.width||b.y+b.height+effectRadius>c.height))push('clipped_effect','warning',l.start,l.start+l.duration,`Effect extent on ${l.id} is clipped by the composition`,'Add padding, reduce the effect radius, or move the layer inward',[l.id]);
    const grid=typeof project.layoutTokens?.alignmentGrid==='number'?project.layoutTokens.alignmentGrid:undefined;if(grid&&((Math.abs(pos(l)[0]/grid-Math.round(pos(l)[0]/grid))>.01)||(Math.abs(pos(l)[1]/grid-Math.round(pos(l)[1]/grid))>.01)))push('alignment','info',l.start,l.start+l.duration,`Layer ${l.id} is off the declared ${grid}px alignment grid`,'Snap the layer to the declared layout grid',[l.id]);
    if(l.layout?.length){try{solveLayout({width:c.width,height:c.height},[{id:l.id,intrinsic:dims(l),constraints:l.layout}]);}catch(error){push('impossible_constraints','error',l.start,l.start+l.duration,`Responsive constraints for ${l.id} are unsatisfiable: ${error instanceof Error?error.message:String(error)}`,'Resolve conflicting size and pin constraints',[l.id]);}}
  }
  for(let i=0;i<visuals.length;i++)for(let j=i+1;j<visuals.length;j++){const a=visuals[i],b=visuals[j];if(overlap(byBounds.get(a.id)!,byBounds.get(b.id)!)){push('collision','warning',Math.max(a.start,b.start),Math.min(a.start+a.duration,b.start+b.duration),`Layers ${a.id} and ${b.id} collide`,'Adjust layout, stacking, or timing to avoid unintended overlap',[a.id,b.id]);const spacing=typeof project.layoutTokens?.spacing==='number'?project.layoutTokens.spacing:undefined;if(spacing&&a.props?.stackGroup&&a.props.stackGroup===b.props?.stackGroup)push('spacing','info',Math.max(a.start,b.start),Math.min(a.start+a.duration,b.start+b.duration),`Stack group ${String(a.props.stackGroup)} violates ${spacing}px spacing`,'Apply the declared stack gap consistently',[a.id,b.id]);}}
  for(const t of c.sharedTransitions??[])if(t.kind!=='hard-cut'&&t.duration<=1)push('transition_discontinuity','warning',t.start,t.start+t.duration,`Transition ${t.id} is too short to preserve continuous shared-element motion`,'Increase transition duration or use an intentional hard cut',t.bindings?.flatMap(b=>[b.sourceLayerId,b.destinationLayerId]));
  const cam=c.cameraId?c.layers.find(l=>l.id===c.cameraId):undefined;if(cam){const k=cam.transform.position.keyframes??[];if(k.length>=3){const velocities:Vec3[]=[];for(let i=1;i<k.length;i++){const dt=k[i].frame-k[i-1].frame;if(dt>0)velocities.push([(k[i].value[0]-k[i-1].value[0])/dt,(k[i].value[1]-k[i-1].value[1])/dt,(k[i].value[2]-k[i-1].value[2])/dt]);}for(let i=1;i<velocities.length;i++)if(norm([velocities[i][0]-velocities[i-1][0],velocities[i][1]-velocities[i-1][1],velocities[i][2]-velocities[i-1][2]])>25){push('camera_velocity','warning',k[i].frame,k[i+1].frame,`Camera ${cam.id} has a velocity discontinuity`,'Smooth camera keyframe velocities or use a continuous curve',[cam.id]);break;}}}
  return{issues,blocking:issues.some(i=>i.severity==='error'),compositionId:c.id};
}
export * from './motion-analysis.ts';
