export type MotionQCIssueType='static_motion_ratio'|'inactive_shot'|'dead_space'|'readability_projection'|'focal_competition'|'end_card_hold'|'cut_only_energy'|'motion_density'|'single_plane_motion'|'ui_occupancy'|'safe_area_spacing';
export interface MotionFrameSample{frame:number;width:number;height:number;luma:number[]}
export interface MotionShotRange{id:string;start:number;end:number}
export interface MotionAnnotation{kind:'intentional-hold'|'ui'|'text'|'activity'|'end-card'|'focal';start:number;end:number;occupancy?:number;projectedPixelHeight?:number;safeMarginPx?:number;independentMotionGroups?:number;activeLayerCount?:number;resolvedAt?:number;layerIds?:string[];weight?:number}
export interface MotionQCConfig{fps:number;staticThreshold?:number;maxStaticRatio?:number;minUiOccupancy?:number;minTextPx?:number;minSafeMarginPx?:number;minEndHoldFrames?:number;minActivePairRatio?:number;cutEnergyRatio?:number}
export interface MotionQCIssue{id:string;type:MotionQCIssueType;severity:'info'|'warning'|'error';startFrame:number;endFrame:number;message:string;suggestion:string;shotId?:string;layerIds?:string[]}
export interface MotionQCMetrics{staticFrameRatio:number;meanMotionEnergy:number;cutEnergyRatio:number;meanOccupancy:number;activePairRatio:number}
export interface MotionQCReport{issues:MotionQCIssue[];blocking:boolean;metrics:MotionQCMetrics}

const clamp01=(n:number)=>Math.max(0,Math.min(1,n));
function inRange(frame:number,a:{start:number;end:number}){return frame>=a.start&&frame<=a.end;}
function diff(a:MotionFrameSample,b:MotionFrameSample):number{if(a.width!==b.width||a.height!==b.height||a.luma.length!==b.luma.length||!a.luma.length)return 1;let sum=0;for(let i=0;i<a.luma.length;i++)sum+=Math.abs((a.luma[i]??0)-(b.luma[i]??0));return sum/(a.luma.length*255);}
function occupancy(frame:MotionFrameSample):number{if(!frame.luma.length)return 0;let n=0;for(const v of frame.luma)if(v>8)n++;return n/frame.luma.length;}
function avg(values:number[]):number{return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}

export function analyzeMotionFrames(frames:MotionFrameSample[],shotRanges:MotionShotRange[],annotations:MotionAnnotation[],config:MotionQCConfig):MotionQCReport{
 const sorted=[...frames].sort((a,b)=>a.frame-b.frame);const threshold=config.staticThreshold??0.003;const maxStatic=config.maxStaticRatio??0.5;const minOcc=config.minUiOccupancy??0.28;const minText=config.minTextPx??18;const minSafe=config.minSafeMarginPx??48;const minHold=config.minEndHoldFrames??45;const minActive=config.minActivePairRatio??0.42;const cutRatio=config.cutEnergyRatio??0.58;
 const holds=annotations.filter(a=>a.kind==='intentional-hold');const boundary=new Set(shotRanges.slice(1).map(s=>s.start));const pairs:Array<{frame:number;energy:number;excluded:boolean;cut:boolean}>=[];
 for(let i=1;i<sorted.length;i++){const frame=sorted[i].frame;const excluded=holds.some(h=>inRange(sorted[i-1].frame,h)&&inRange(frame,h));pairs.push({frame,energy:diff(sorted[i-1],sorted[i]),excluded,cut:boundary.has(frame)});}
 const considered=pairs.filter(p=>!p.excluded),staticPairs=considered.filter(p=>p.energy<threshold),totalEnergy=considered.reduce((s,p)=>s+p.energy,0),cutEnergy=considered.filter(p=>p.cut||boundary.has(p.frame-1)||boundary.has(p.frame+1)).reduce((s,p)=>s+p.energy,0);const active=considered.filter(p=>p.energy>=threshold);
 const metrics:MotionQCMetrics={staticFrameRatio:considered.length?staticPairs.length/considered.length:0,meanMotionEnergy:avg(considered.map(p=>p.energy)),cutEnergyRatio:totalEnergy>1e-9?cutEnergy/totalEnergy:0,meanOccupancy:avg(sorted.map(occupancy)),activePairRatio:considered.length?active.length/considered.length:0};
 const issues:MotionQCIssue[]=[];let seq=0;const push=(type:MotionQCIssueType,severity:MotionQCIssue['severity'],startFrame:number,endFrame:number,message:string,suggestion:string,extra:Partial<MotionQCIssue>={})=>issues.push({id:`mq_${String(++seq).padStart(3,'0')}`,type,severity,startFrame,endFrame,message,suggestion,...extra});
 if(metrics.staticFrameRatio>maxStatic)push('static_motion_ratio','error',sorted[0]?.frame??0,sorted.at(-1)?.frame??0,`${Math.round(metrics.staticFrameRatio*100)}% of non-hold frame pairs are effectively static`,`Add meaningful in-shot subject/background/foreground motion or annotate a deliberate hero hold`);
 if(metrics.activePairRatio<minActive)push('motion_density','warning',sorted[0]?.frame??0,sorted.at(-1)?.frame??0,`Only ${Math.round(metrics.activePairRatio*100)}% of frame pairs contain meaningful motion`,`Increase sustained animation density instead of relying on scene changes`);
 if(metrics.cutEnergyRatio>cutRatio)push('cut_only_energy','error',sorted[0]?.frame??0,sorted.at(-1)?.frame??0,`${Math.round(metrics.cutEnergyRatio*100)}% of measured motion energy occurs at shot boundaries`,`Move visual energy inside shots with continuous transforms, stagger, camera depth or procedural motion`);
 if(metrics.meanOccupancy<.18)push('dead_space','warning',sorted[0]?.frame??0,sorted.at(-1)?.frame??0,`Average occupied picture area is only ${Math.round(metrics.meanOccupancy*100)}%`,`Increase meaningful product/detail coverage or add supporting dimensional background structure`);
 for(const shot of shotRanges){const p=considered.filter(x=>x.frame>shot.start&&x.frame<=shot.end),ratio=p.length?p.filter(x=>x.energy>=threshold).length/p.length:0;if(shot.end-shot.start+1>Math.max(2,config.fps*.5)&&ratio<.35&&!holds.some(h=>h.start<=shot.start&&h.end>=shot.end))push('inactive_shot','warning',shot.start,shot.end,`Shot ${shot.id} is visually inactive for most of its duration`,`Add at least two independently changing visual properties or shorten the shot`,{shotId:shot.id});}
 for(const a of annotations){if(a.kind==='ui'&&a.occupancy!==undefined){if(a.occupancy<minOcc)push('ui_occupancy','warning',a.start,a.end,`Hero UI occupies only ${Math.round(a.occupancy*100)}% of the frame`,`Use a closer product crop or camera move so the interface remains readable`,{layerIds:a.layerIds});if(a.occupancy<.18)push('dead_space','warning',a.start,a.end,'UI framing leaves excessive inactive canvas around the product','Recompose around the active product surface or add purposeful supporting layers',{layerIds:a.layerIds});}
  if(a.kind==='text'&&a.projectedPixelHeight!==undefined&&a.projectedPixelHeight<minText)push('readability_projection','error',a.start,a.end,`Projected text height is ${a.projectedPixelHeight.toFixed(1)} px`,`Increase native type size or camera scale until projected glyph bounds meet the ${minText}px floor`,{layerIds:a.layerIds});
  if((a.kind==='text'||a.kind==='ui')&&a.safeMarginPx!==undefined&&a.safeMarginPx<minSafe)push('safe_area_spacing','warning',a.start,a.end,`Important content is only ${a.safeMarginPx.toFixed(0)} px from the safe boundary`,`Increase edge spacing to at least ${minSafe}px`,{layerIds:a.layerIds});
  if(a.kind==='activity'&&(a.independentMotionGroups??0)<2&&(a.end-a.start+1)>config.fps)push('single_plane_motion','error',a.start,a.end,'Long section is driven by a single motion group/global transform','Create independent foreground, subject and background motion with separate timing curves',{layerIds:a.layerIds});
  if(a.kind==='end-card'){const resolved=a.resolvedAt??a.start,hold=a.end-resolved+1;if(hold<minHold)push('end_card_hold','error',resolved,a.end,`Resolved end card holds for only ${hold} frames`,`Hold the fully resolved brand/payoff frame for at least ${minHold} frames`,{layerIds:a.layerIds});}
 }
 const focal=annotations.filter(a=>a.kind==='focal');for(let i=0;i<focal.length;i++)for(let j=i+1;j<focal.length;j++){const a=focal[i],b=focal[j],start=Math.max(a.start,b.start),end=Math.min(a.end,b.end);if(start<=end&&(a.weight??1)>.65&&(b.weight??1)>.65)push('focal_competition','warning',start,end,'Multiple high-priority focal elements compete simultaneously','Sequence emphasis or reduce one element’s contrast/motion',{layerIds:[...(a.layerIds??[]),...(b.layerIds??[])]});}
 return{issues,blocking:issues.some(i=>i.severity==='error'),metrics:{...metrics,staticFrameRatio:clamp01(metrics.staticFrameRatio),cutEnergyRatio:clamp01(metrics.cutEnergyRatio),activePairRatio:clamp01(metrics.activePairRatio)}};
}
