import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {GenerationProviderRegistry,acceptRankedGenerationCandidates,type GenerationProvider,type ProviderCapabilityManifest,type StagedGenerationOutput} from '../../packages/generation/src/index.ts';
import {buildLocalInterpolationRequest,routeLocalShot} from '../../packages/generated-scenes/src/index.ts';
import {buildDeterministicBrandLayers,planDeterministicBrandFinish,type ProductIdentityPackage} from '../../packages/product-fidelity/src/index.ts';

const localVideo:GenerationProvider={manifest:():ProviderCapabilityManifest=>({provider:'wan-local',kinds:['video'],execution:'local',supportsTransparency:false,supportsMasks:true,supportsReferences:true,supportsStreaming:false,supportsCancellation:true,estimatedUnit:'second',estimatedCostUnits:0,video:{supportsFirstFrame:true,supportsLastFrame:true,maxReferenceImages:4,supportsNegativePrompt:true,supportsSeed:true,minDurationSeconds:1,maxDurationSeconds:10,supportedResolutions:['720p'],supportedAspectRatios:['16:9'],supportsCameraControl:true,supportsMotionMasks:true,supportsExtension:false,supportsNativeAudio:false}}),generate:async()=>({requestId:'video',provider:'wan-local',model:'fixture',outputs:[]})};

test('complex product shot can stay fully local from routing through guarded acceptance and native brand finish',()=>{const route=routeLocalShot({id:'splash-orbit',kind:'fluid',fluidMotion:true,cameraRotationDegrees:15,referenceImageCount:2,requiresExactProductGeometry:true,durationSeconds:4,resolution:'720p',aspectRatio:'16:9',useLastFrameAnchor:true,useMotionMask:true},'standard-gpu');assert.equal(route.strategy,'local-video');const request=buildLocalInterpolationRequest({projectId:'p',requestId:'video',prompt:'cold product splash with controlled camera arc',firstAnchorAssetId:'front-anchor',lastAnchorAssetId:'end-anchor',referenceAssetIds:['side'],durationSeconds:4,resolution:'720p',aspectRatio:'16:9',camera:{orbitDegrees:15},motionMaskAssetIds:['fluid-mask'],hardwareProfile:'standard-gpu',candidateCount:2,seed:4});const registry=new GenerationProviderRegistry();registry.register(localVideo);assert.equal(registry.resolve(request,route.requirements).manifest().provider,'wan-local');const root=mkdtempSync(join(tmpdir(),'local-integration-')),bad=join(root,'bad.mp4'),good=join(root,'good.mp4');writeFileSync(bad,'bad');writeFileSync(good,'good');const staged:StagedGenerationOutput={requestId:'video',provider:'wan-local',model:'fixture',outputs:[{path:bad,mediaType:'video/mp4',sha256:''},{path:good,mediaType:'video/mp4',sha256:''}],usage:{costUsd:0}};const identity:ProductIdentityPackage={id:'drink',name:'Drink',approvedAssetIds:['front','side'],expectedOcrStrings:['BRAND'],logoReferenceAssetIds:['logo'],silhouetteReferenceAssetId:'front',protectedColors:[{name:'brand',referenceLab:[80,-50,30]}],protectedRegionAssetIds:['front']};try{const accepted=acceptRankedGenerationCandidates(request,staged,identity,[{outputIndex:0,measurements:{observedOcrStrings:['B?AND'],logoSimilarity:.4,silhouetteSimilarity:.65,colorSimilarity:.7,segmentationStability:.7,temporalConsistency:.6,flickerScore:.4,cameraAdherence:.3,productOccupancy:.4,aestheticScore:.95,promptAdherence:.9}},{outputIndex:1,measurements:{observedOcrStrings:['BRAND'],logoSimilarity:.99,silhouetteSimilarity:.98,colorSimilarity:.97,segmentationStability:.96,temporalConsistency:.94,flickerScore:.04,cameraAdherence:.9,productOccupancy:.5,aestheticScore:.8,promptAdherence:.9}}],join(root,'assets'),{generationQC:{requireCameraAdherence:true}});assert.equal(accepted.acceptance.assets.length,1);assert.deepEqual(accepted.ranking.filter(x=>x.approved).map(x=>x.outputIndex),[1]);const finish=planDeterministicBrandFinish(identity,accepted.acceptance.assets[0].id),placements=Object.fromEntries(finish.instructions.map((x,i)=>[x.id,{position:[100+i*100,100,0] as const,fontSize:42}])),layers=buildDeterministicBrandLayers(finish,120,placements);assert.ok(layers.length>0);assert.ok(layers.every(l=>l.locked&&l.props?.generatedByModel===false));assert.equal(staged.usage?.costUsd,0)}finally{rmSync(root,{recursive:true,force:true})}});
