import { McpDesktopClient, startDesktopProject } from './mcp-client.js';

const $=id=>document.getElementById(id);let client=null,timelineState=null,selected=null;
const setStatus=(message,kind='')=>{const el=$('status');el.textContent=message;el.dataset.kind=kind;};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function refresh(){if(!client)return;timelineState=await client.getTimeline();$('revision').textContent=`revision ${timelineState.revision}`;renderTimeline();renderBuses();renderMulticam();await refreshDiagnostics();}
function root(){return timelineState?.project?.compositions?.find(c=>c.id===timelineState.project.rootCompositionId)??timelineState?.project?.compositions?.[0];}
function renderTimeline(){const target=$('timeline');target.textContent='';const composition=root();if(!composition){target.innerHTML='<p class="empty">Project has no composition.</p>';return;}for(const track of composition.tracks){const row=document.createElement('div');row.className='track';row.innerHTML=`<label>${escapeHtml(track.name??track.id)} <small>${escapeHtml(track.kind)}</small></label><div class="clips"></div>`;const clips=row.querySelector('.clips');for(const clip of track.clips){const button=document.createElement('button');button.className='clip';button.style.setProperty('--start',String(clip.start??0));button.textContent=`${clip.id} · ${clip.start}–${clip.start+clip.duration}`;button.addEventListener('click',()=>selectClip(composition.id,track.id,clip));clips.append(button);}target.append(row);}}
function selectClip(compositionId,trackId,clip){selected={compositionId,trackId,clipId:clip.id};$('selection').textContent=`${trackId} / ${clip.id}`;$('opacity').value=String(clip.opacity??1);const t=clip.transform??{};$('tx').value=String(t.x??0);$('ty').value=String(t.y??0);$('tsx').value=String(t.scaleX??1);$('tsy').value=String(t.scaleY??1);$('tr').value=String(t.rotation??0);$('effectStack').textContent=JSON.stringify(clip.effectStack??[],null,2);}
async function edit(name,args){if(!client||!timelineState)throw new Error('Open a project first');const result=await client.callTool(name,{expectedRevision:timelineState.revision,...args});if(result?.ok===false)throw new Error(result.conflict?.message??'Project revision conflict');await refresh();return result;}
function renderBuses(){const el=$('buses');el.textContent='';for(const bus of timelineState?.project?.audioBuses??[]){const row=document.createElement('label');row.className='bus';row.innerHTML=`<span>${escapeHtml(bus.name??bus.id)}</span><input type="number" step="0.5" value="${Number(bus.gainDb??0)}"><small>dB</small>`;row.querySelector('input').addEventListener('change',e=>edit('set_audio_bus_gain',{busId:bus.id,gainDb:Number(e.target.value),intent:'Desktop mixer'}).catch(showError));el.append(row);}}
function renderMulticam(){const el=$('multicam');el.textContent='';for(const group of timelineState?.project?.multicamGroups??[]){const title=document.createElement('div');title.className='mc-title';title.textContent=group.name??group.id;el.append(title);for(const angle of group.angles??[]){const b=document.createElement('button');b.textContent=angle.id;b.addEventListener('click',()=>{const comp=root();const end=Math.max(1,...(comp?.tracks??[]).flatMap(t=>(t.clips??[]).map(c=>c.start+c.duration)));edit('switch_multicam_angle',{groupId:group.id,start:0,end,angleId:angle.id,intent:'Desktop multicam switch'}).catch(showError);});el.append(b);}}}
async function refreshDiagnostics(){if(!client)return;const [preview,diagnostics]=await Promise.all([client.callTool('get_preview_capabilities',{}),client.callTool('get_render_diagnostics',{})]);$('previewCapabilities').textContent=`Preview: ${preview.backend} · ${preview.available?'available':'fallback'}${preview.reason?` · ${preview.reason}`:''}`;$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);}
function showError(error){$('sys').textContent=error instanceof Error?error.message:String(error);setStatus('Action failed','error');}
$('openProject').addEventListener('click',async()=>{try{const invoke=window.__TAURI__?.core?.invoke;if(!invoke)throw new Error('Open the packaged Tauri app to start a project session');setStatus('Starting canonical project engine…');const session=await startDesktopProject(invoke,$('projectPath').value);client=session.client;setStatus(`Project engine · ${session.endpoint}`,'ok');await refresh();}catch(e){showError(e);}});
$('applyTransform').addEventListener('click',()=>{if(!selected)return showError(new Error('Select a clip first'));edit('set_transform',{compositionId:selected.compositionId,clipId:selected.clipId,transform:{x:Number($('tx').value),y:Number($('ty').value),scaleX:Number($('tsx').value),scaleY:Number($('tsy').value),rotation:Number($('tr').value)},intent:'Desktop transform'}).catch(showError);});
$('opacity').addEventListener('change',()=>{if(!selected)return;edit('set_opacity',{compositionId:selected.compositionId,clipId:selected.clipId,opacity:Number($('opacity').value),intent:'Desktop opacity'}).catch(showError);});
$('refreshDiagnostics').addEventListener('click',()=>refreshDiagnostics().catch(showError));
$('cap').addEventListener('click',async()=>{try{const invoke=window.__TAURI__?.core?.invoke;if(!invoke)throw new Error('Running as browser preview');$('sys').textContent=JSON.stringify(await invoke('desktop_capabilities'),null,2);}catch(e){showError(e);}});
void McpDesktopClient; // keep the canonical client visible to static packaging audits.
