import type { GenerationRequest, ProviderCapabilityManifest } from '../../generation/src/types.ts';
import type { GeneratedSceneRequest } from '../../generated-scenes/src/types.ts';
import type { AspectClass } from '../../schema/src/v3/project.ts';
import type { V3EditOperation } from '../../timeline/src/v3.ts';
export type CreativeAction=|{id:string;type:'search_media';beatId:string;query:string;rationale:string}|{id:string;type:'place_evidence';beatId:string;assetId:string;start:number;end:number;targetCompositionId:string;rationale:string}|{id:string;type:'generate_asset';beatId:string;request:GenerationRequest;rationale:string}|{id:string;type:'build_generated_scene';beatId:string;sourceActionId?:string;request?:GeneratedSceneRequest;rationale:string}|{id:string;type:'apply_motion';beatId?:string;operation:V3EditOperation;rationale:string}|{id:string;type:'create_variant';sourceCompositionId:string;aspect:AspectClass;rationale:string}|{id:string;type:'qc';scope:{compositionId:string;start?:number;end?:number};rationale:string}|{id:string;type:'craft_review';compositionId:string;minimumScore?:number;rationale:string}|{id:string;type:'repair';scope:{compositionId:string;layerIds?:string[];range?:{start:number;end:number}};strategy:string;rationale:string};
export interface CreativeActionPlan{version:1;briefId:string;baseRevision:string;actions:CreativeAction[];dependencies:Record<string,string[]>}
export interface CreativePlanValidationContext{assetIds:Set<string>;compositionIds:Set<string>;beatIds:Set<string>;motionStyleIds:Set<string>;providers:ProviderCapabilityManifest[]}
const executable=/^(command|commands|shell|javascript|executable|exec|eval|script|scripts|code|function|child_process)$/i;
function scan(value:unknown,path='plan',depth=0):void{if(depth>32)throw new Error(`Creative plan nesting exceeds limit at ${path}`);if(typeof value==='function')throw new Error(`Executable function is not allowed at ${path}`);if(Array.isArray(value)){if(value.length>10_000)throw new Error(`Creative plan action budget exceeded at ${path}`);value.forEach((item,index)=>scan(item,`${path}[${index}]`,depth+1));return}if(value&&typeof value==='object')for(const[key,nested]of Object.entries(value as Record<string,unknown>)){if(executable.test(key))throw new Error(`Executable field ${key} is not allowed at ${path}`);scan(nested,`${path}.${key}`,depth+1)}}
function nonEmpty(value:string,name:string):void{if(typeof value!=='string'||!value.trim())throw new Error(`${name} is required`)}function validRange(start:number,end:number,name:string):void{if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end<=start)throw new Error(`${name} range is invalid`)}
function validateDependencies(plan:CreativeActionPlan,ids:Set<string>):void{for(const[id,dependencies]of Object.entries(plan.dependencies)){if(!ids.has(id))throw new Error(`Unknown dependency owner ${id}`);for(const dependency of dependencies)if(!ids.has(dependency))throw new Error(`Unknown dependency ${dependency} for ${id}`)}for(const id of ids)if(!plan.dependencies[id])plan.dependencies[id]=[];const visiting=new Set<string>(),done=new Set<string>();const visit=(id:string):void=>{if(done.has(id))return;if(visiting.has(id))throw new Error(`Creative action dependency cycle at ${id}`);visiting.add(id);for(const dependency of plan.dependencies[id]??[])visit(dependency);visiting.delete(id);done.add(id)};for(const id of ids)visit(id)}
export function validateCreativeActionPlan(input:CreativeActionPlan,context:CreativePlanValidationContext):CreativeActionPlan{scan(input);if(input.version!==1)throw new Error('Unsupported creative action plan version');nonEmpty(input.briefId,'briefId');nonEmpty(input.baseRevision,'baseRevision');if(input.actions.length<1||input.actions.length>10_000)throw new Error('Creative action budget exceeded');const ids=new Set<string>();for(const action of input.actions){nonEmpty(action.id,'action.id');if(ids.has(action.id))throw new Error(`Duplicate creative action id ${action.id}`);ids.add(action.id);nonEmpty(action.rationale,`${action.id}.rationale`);if('beatId'in action&&action.beatId&&!context.beatIds.has(action.beatId))throw new Error(`Unknown beat ${action.beatId}`);switch(action.type){case'place_evidence':validRange(action.start,action.end,action.id);if(!context.assetIds.has(action.assetId))throw new Error(`Unknown asset ${action.assetId}`);if(!context.compositionIds.has(action.targetCompositionId))throw new Error(`Unknown composition ${action.targetCompositionId}`);break;case'generate_asset':if(!context.providers.some(provider=>provider.kinds.includes(action.request.kind)))throw new Error(`No provider supports generation kind ${action.request.kind}`);break;case'build_generated_scene':if(action.request&&!context.compositionIds.has(action.request.compositionId))throw new Error(`Unknown composition ${action.request.compositionId}`);break;case'apply_motion':{const operation=action.operation as V3EditOperation&{compositionId?:string};const compositionId=operation.compositionId;if(compositionId&&!context.compositionIds.has(compositionId)&&operation.type!=='create_motion_composition')throw new Error(`Unknown composition ${compositionId}`);break}case'create_variant':if(!context.compositionIds.has(action.sourceCompositionId))throw new Error(`Unknown composition ${action.sourceCompositionId}`);break;case'qc':if(!context.compositionIds.has(action.scope.compositionId))throw new Error(`Unknown composition ${action.scope.compositionId}`);if(action.scope.start!==undefined||action.scope.end!==undefined)validRange(action.scope.start??0,action.scope.end??0,action.id);break;case'craft_review':if(!context.compositionIds.has(action.compositionId))throw new Error(`Unknown composition ${action.compositionId}`);if(action.minimumScore!==undefined&&(!Number.isFinite(action.minimumScore)||action.minimumScore<0||action.minimumScore>100))throw new Error('craft review minimumScore must be between 0 and 100');break;case'repair':if(!context.compositionIds.has(action.scope.compositionId))throw new Error(`Unknown composition ${action.scope.compositionId}`);if(action.scope.range)validRange(action.scope.range.start,action.scope.range.end,action.id);break;case'search_media':nonEmpty(action.query,`${action.id}.query`);break}}
const clone=structuredClone(input);validateDependencies(clone,new Set(clone.actions.map(action=>action.id)));return clone}
