import test from 'node:test';
import assert from 'node:assert/strict';
import { validateCreativeActionPlan,type CreativeActionPlan,type CreativePlanValidationContext } from './actions.ts';

const context:CreativePlanValidationContext={assetIds:new Set(['asset']),compositionIds:new Set(['comp']),beatIds:new Set(['hook','demo']),motionStyleIds:new Set(),providers:[{provider:'fixture',kinds:['image'],execution:'local',supportsTransparency:true,supportsMasks:false,supportsReferences:false,supportsStreaming:false,supportsCancellation:true}]};
const valid=():CreativeActionPlan=>({version:1,briefId:'brief',baseRevision:'rev',actions:[{id:'a',type:'place_evidence',beatId:'hook',assetId:'asset',start:0,end:30,targetCompositionId:'comp',rationale:'Strong matching source evidence exists.'},{id:'q',type:'qc',scope:{compositionId:'comp',start:0,end:30},rationale:'Verify the placed evidence.'}],dependencies:{a:[],q:['a']}});

test('creative action plans validate declarative references and dependencies',()=>{assert.equal(validateCreativeActionPlan(valid(),context).actions.length,2)});
test('creative plans reject duplicate IDs, cycles, missing rationales and invalid ranges',()=>{const duplicate=valid();duplicate.actions.push({...duplicate.actions[0],rationale:'other'});assert.throws(()=>validateCreativeActionPlan(duplicate,context),/Duplicate/);const cycle=valid();cycle.dependencies.a=['q'];assert.throws(()=>validateCreativeActionPlan(cycle,context),/cycle/i);const noRationale=valid();(noRationale.actions[0] as any).rationale='';assert.throws(()=>validateCreativeActionPlan(noRationale,context),/rationale/i);const badRange=valid();(badRange.actions[0] as any).end=0;assert.throws(()=>validateCreativeActionPlan(badRange,context),/range/i)});
test('creative plans reject unknown dependencies, executable fields and oversized action sets',()=>{const unknown=valid();unknown.dependencies.q=['missing'];assert.throws(()=>validateCreativeActionPlan(unknown,context),/dependency/i);const executable=valid() as any;executable.actions[0].command='rm -rf /';assert.throws(()=>validateCreativeActionPlan(executable,context),/executable/i);const oversized=valid();oversized.actions=Array.from({length:10001},(_,i)=>({...valid().actions[1],id:`q${i}`}));oversized.dependencies=Object.fromEntries(oversized.actions.map(a=>[a.id,[]]));assert.throws(()=>validateCreativeActionPlan(oversized,context),/budget/i)});
test('generation actions require known beat and provider-compatible request',()=>{const p=valid();p.actions.splice(1,0,{id:'g',type:'generate_asset',beatId:'demo',request:{id:'req',projectId:'p',kind:'image',prompt:'Missing product hero',inputAssetIds:[],parameters:{}},rationale:'No source evidence satisfies the required demo beat.'});p.dependencies.g=[];p.dependencies.q=['a','g'];assert.doesNotThrow(()=>validateCreativeActionPlan(p,context));(p.actions[1] as any).beatId='missing';assert.throws(()=>validateCreativeActionPlan(p,context),/beat/i)});
