import test from 'node:test';
import assert from 'node:assert/strict';
import { CreativePlanExecutor,type CreativeExecutionContext } from './executor.ts';
import type { CreativeActionPlan } from './actions.ts';

const plan:CreativeActionPlan={version:1,briefId:'brief',baseRevision:'r0',actions:[{id:'e',type:'place_evidence',beatId:'hook',assetId:'asset',start:0,end:20,targetCompositionId:'comp',rationale:'Use existing evidence.'},{id:'g',type:'generate_asset',beatId:'demo',request:{id:'req',projectId:'p',kind:'image',prompt:'hero',inputAssetIds:[],parameters:{}},rationale:'Required beat has no suitable evidence.'},{id:'q',type:'qc',scope:{compositionId:'comp'},rationale:'Verify final composition.'}],dependencies:{e:[],g:['e'],q:['g']}};
function context(log:string[]=[]):CreativeExecutionContext{return{project:{} as any,revision:'r0',generation:{} as any,adapters:{placeEvidence:async(action,revision)=>{log.push(action.id);return{revision:revision+'e',receipt:{placed:true}}},generateAsset:async(action,revision)=>{log.push(action.id);return{revision:revision+'g',receipt:{jobId:'j',accepted:true}}},qc:async(action,revision)=>{log.push(action.id);return{revision,receipt:{issues:[]}}}}}}

test('executor follows dependencies, propagates revisions and records receipts',async()=>{const log:string[]=[];const receipt=await new CreativePlanExecutor().execute(plan,context(log));assert.deepEqual(log,['e','g','q']);assert.deepEqual(receipt.completedActionIds,['e','g','q']);assert.equal(receipt.projectRevision,'r0eg');assert.equal((receipt.actionReceipts.g as any).jobId,'j')});
test('executor aborts cleanly and resume skips completed actions',async()=>{const log:string[]=[];const ctx=context(log);let first=true;ctx.adapters.generateAsset=async()=>{if(first){first=false;throw new Error('provider timeout')}return{revision:'r0eg',receipt:{jobId:'j2'}}};const executor=new CreativePlanExecutor(),partial=await executor.execute(plan,ctx);assert.equal(partial.failedActionId,'g');assert.deepEqual(partial.completedActionIds,['e']);const resumed=await executor.resume(plan,partial,ctx);assert.deepEqual(resumed.completedActionIds,['e','g','q']);assert.equal(log.filter(x=>x==='e').length,1)});
test('executor honors AbortSignal before starting another action',async()=>{const controller=new AbortController(),log:string[]=[];const ctx=context(log);ctx.adapters.placeEvidence=async(action,revision)=>{controller.abort();log.push(action.id);return{revision:revision+'e',receipt:{}}};const receipt=await new CreativePlanExecutor().execute(plan,ctx,controller.signal);assert.deepEqual(receipt.completedActionIds,['e']);assert.equal(receipt.failedActionId,'g')});
