import test from 'node:test';
import assert from 'node:assert/strict';
import { migrateV2ToV3,animated,defaultMotionTransform,type FlickProjectV2 } from '../../schema/src/index.ts';
import { planResponsiveVariants } from './variants.ts';

function project(){const v2:FlickProjectV2={version:2,id:'p',name:'P',format:{width:1920,height:1080,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[],rootCompositionId:'root',compositions:[{id:'root',name:'Root',width:1920,height:1080,tracks:[]}],audioBuses:[],multicamGroups:[],perception:{providers:[]},preview:{quality:'full',preferGpu:false},markers:[],style:{},provenance:[],checkpoints:[],branches:[]};const p=migrateV2ToV3(v2);p.motionCompositions.push({id:'hero',name:'Hero',width:1920,height:1080,duration:120,background:'#000000',layers:[{id:'logo',kind:'image',name:'Logo',start:0,duration:120,enabled:true,locked:false,zIndex:2,transform:{...defaultMotionTransform(),position:animated([160,100,0])},opacity:animated(1),effects:[],masks:[],motionBlur:false,props:{width:240,height:100,semanticPreserve:true}},{id:'cta',kind:'text',name:'CTA',start:60,duration:60,enabled:true,locked:false,zIndex:3,transform:{...defaultMotionTransform(),position:animated([960,860,0])},opacity:animated(1),effects:[],masks:[],motionBlur:false,text:'Build now',textStyle:{fontSize:animated(64)},props:{width:480,height:120,semanticPreserve:true}}]});return p}

test('responsive variants reuse source composition and preserve semantic layers',()=>{const ops=planResponsiveVariants(project(),{sourceCompositionId:'hero',aspects:['portrait','square','four-five'],preserveLayerIds:['logo','cta']});assert.equal(ops.length,3);for(const op of ops){assert.equal(op.type,'set_responsive_variant');if(op.type!=='set_responsive_variant')continue;assert.deepEqual(Object.keys(op.variant.constraintsByLayer).sort(),['cta','logo']);for(const constraints of Object.values(op.variant.constraintsByLayer)){assert.ok(constraints.some(c=>c.type==='safe-area'));assert.ok(constraints.some(c=>/center|pin/.test(c.type)))}}});
test('variants reject missing preserved layers instead of silently cropping them',()=>{assert.throws(()=>planResponsiveVariants(project(),{sourceCompositionId:'hero',aspects:['portrait'],preserveLayerIds:['missing']}),/missing/i)});
