import type { FrameRange, RenderGraph } from '../../render-graph/src/index.ts';
export type PreviewBackend='webgpu'|'native'|'software'|'unavailable';
export type PreviewQuality='full'|'half'|'quarter'|'proxy';
export interface PreviewCapabilities { backend:PreviewBackend; available:boolean; webGpu?:boolean; webCodecs?:boolean; detail?:string }
export interface PreviewFrame { frame:number;width:number;height:number;rgba:Uint8Array }
export interface PreviewRenderer { capabilities():Promise<PreviewCapabilities>; load(graph:RenderGraph):Promise<void>; seek(frame:number):Promise<PreviewFrame>; invalidate(range:FrameRange):Promise<void>; dispose():Promise<void> }
export interface EnvironmentCapabilities { webGpu:boolean;webCodecs:boolean;nativeGpu:boolean;software:boolean }
export function selectPreviewBackend(c:EnvironmentCapabilities):{backend:PreviewBackend;reason:string}{if(c.webGpu&&c.webCodecs)return{backend:'webgpu',reason:'WebGPU and decode available'};if(c.nativeGpu)return{backend:'native',reason:'native GPU fallback'};if(c.software)return{backend:'software',reason:'software/proxy fallback'};return{backend:'unavailable',reason:'no usable preview backend'};}
export class AdaptiveQualityController { quality:PreviewQuality; private misses=0;private good=0;constructor(initial:PreviewQuality='full'){this.quality=initial;}observe(frameMs:number,budgetMs:number){if(frameMs>budgetMs){this.misses++;this.good=0;if(this.misses>=3){this.down();this.misses=0;}}else if(frameMs<budgetMs*.65){this.good++;this.misses=0;if(this.good>=20){this.up();this.good=0;}}else{this.misses=0;this.good=0;}}private down(){this.quality=this.quality==='full'?'half':this.quality==='half'?'quarter':this.quality==='quarter'?'proxy':'proxy';}private up(){this.quality=this.quality==='proxy'?'quarter':this.quality==='quarter'?'half':this.quality==='half'?'full':'full';}}
export function chooseRecoveryBackend(c:{nativeGpu:boolean;software:boolean}):'native'|'software'|'unavailable'{return c.nativeGpu?'native':c.software?'software':'unavailable';}
export interface FrameComparison { pixelRmse:number;alphaRmse:number;maxChannelError:number }
export function compareFrames(a:Uint8Array,b:Uint8Array,width:number,height:number):FrameComparison {if(a.length!==b.length||a.length!==width*height*4)throw new Error('RGBA frame dimensions differ');let rgb=0,alpha=0,max=0;for(let i=0;i<a.length;i+=4){for(let c=0;c<3;c++){const d=Math.abs(a[i+c]-b[i+c])/255;rgb+=d*d;max=Math.max(max,d);}const d=Math.abs(a[i+3]-b[i+3])/255;alpha+=d*d;max=Math.max(max,d);}return{pixelRmse:Math.sqrt(rgb/(width*height*3)),alphaRmse:Math.sqrt(alpha/(width*height)),maxChannelError:max};}
export function assertDeclaredApproximation(name:string,support:'native'|'approximate'|'unsupported',tolerance?:{pixelRmse?:number;alphaRmse?:number;timingFrames?:number}){if(support==='approximate'&&(!tolerance||Object.keys(tolerance).length===0))throw new Error(`Approximate ${name} requires a declared tolerance`);if(support==='unsupported')throw new Error(`${name} is unsupported`);}
export type BenchmarkInput={status:'blocked';backend:string;reason:string}|{status:'measured';backend:string;frameTimesMs:number[];seekLatenciesMs:number[];droppedFrames:number;totalFrames:number;cacheHits:number;cacheMisses:number};
export interface BenchmarkReport {status:'blocked'|'measured';backend:string;reason?:string;fps:number|null;p50FrameMs:number|null;p95FrameMs:number|null;p95SeekMs:number|null;droppedFrames:number|null;cacheHitRate:number|null}
function percentile(values:number[],p:number){if(!values.length)return null;const s=[...values].sort((a,b)=>a-b);return s[Math.min(s.length-1,Math.ceil(p*s.length)-1)];}
export function summarizeBenchmark(i:BenchmarkInput):BenchmarkReport {if(i.status==='blocked')return{status:'blocked',backend:i.backend,reason:i.reason,fps:null,p50FrameMs:null,p95FrameMs:null,p95SeekMs:null,droppedFrames:null,cacheHitRate:null};if(!i.frameTimesMs.length)throw new Error('measured benchmark requires frame times');const avg=i.frameTimesMs.reduce((a,b)=>a+b,0)/i.frameTimesMs.length;return{status:'measured',backend:i.backend,fps:1000/avg,p50FrameMs:percentile(i.frameTimesMs,.5)!,p95FrameMs:percentile(i.frameTimesMs,.95)!,p95SeekMs:percentile(i.seekLatenciesMs,.95),droppedFrames:i.droppedFrames,cacheHitRate:(i.cacheHits+i.cacheMisses)?i.cacheHits/(i.cacheHits+i.cacheMisses):0};}
