import test from 'node:test';
import assert from 'node:assert/strict';
import { migrateV2ToV3, type FlickProjectV2 } from '../../../packages/schema/src/index.ts';
import { GenerationProviderRegistry, GenerationRuntime } from '../../../packages/generation/src/index.ts';
import { JobStore } from '../../../packages/jobs/src/store.ts';
import { JobScheduler } from '../../../packages/jobs/src/scheduler.ts';
import { V3FlickSmithHost } from './host-v3.ts';
import { v3ToolCatalog } from './tools.ts';

function project(){const v2:FlickProjectV2={version:2,id:'p',name:'P',format:{width:100,height:100,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[],rootCompositionId:'root',compositions:[{id:'root',name:'Root',width:100,height:100,tracks:[]}],audioBuses:[],multicamGroups:[],perception:{providers:[]},preview:{quality:'full',preferGpu:false},markers:[],style:{},provenance:[],checkpoints:[],branches:[]};return migrateV2ToV3(v2)}
test('v3 catalog exposes provider-neutral generation lifecycle with no credential fields',()=>{for(const name of ['list_generation_providers','generate_asset','get_generation_job','cancel_generation','accept_generation','discard_generation'])assert.ok(v3ToolCatalog.some(t=>t.name===name),name);const serialized=JSON.stringify(v3ToolCatalog);assert.doesNotMatch(serialized,/apiKey|password|secret/i)});
test('generation stages without revision change and explicit acceptance changes revision',async()=>{const registry=new GenerationProviderRegistry();registry.register({manifest:()=>({provider:'fake',kinds:['image'],execution:'local',supportsTransparency:false,supportsMasks:false,supportsReferences:false,supportsStreaming:false,supportsCancellation:true}),generate:async()=>({requestId:'r',provider:'fake',model:'m',outputs:[]})});const store=new JobStore(),scheduler=new JobScheduler(store,{cpu:1,io:1,gpu:1,model:1}),generation=new GenerationRuntime({registry,scheduler,stagingRoot:process.cwd()});const host=new V3FlickSmithHost({project:project(),generation});const before=host.revision;const submitted=await host.call('generate_asset',{request:{id:'r',projectId:'p',kind:'image',inputAssetIds:[],parameters:{}}}) as any;assert.equal(host.revision,before);await scheduler.runUntilIdle();const status=await host.call('get_generation_job',{jobId:submitted.jobId}) as any;assert.equal(status.job.state,'completed');assert.equal(host.revision,before);store.close()});
