import test from 'node:test';import assert from 'node:assert/strict';
import { migrateV1ToV2 } from '../../../packages/schema/src/index.ts';import type { FlickProject } from '../../../packages/schema/src/project.ts';
import { V2ProjectSession } from '../../../packages/timeline/src/index.ts';import { StudioEditController, ProgramMonitorController, RepairController } from './controllers.ts';
const v1:FlickProject={version:1,id:'p',name:'P',format:{width:100,height:100,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[{id:'a',path:'/tmp/a.mp4',kind:'video'}],tracks:[{id:'v',kind:'video',name:'V',clips:[{id:'c',assetId:'a',start:0,duration:60,sourceIn:0}]}],markers:[],style:{},provenance:[],checkpoints:[],branches:[]};
test('studio controls route through canonical v2 mutations',()=>{const p=migrateV1ToV2(v1);p.audioBuses.push({id:'music',name:'Music',effects:[],gainDb:0,pan:0,outputBusId:'master'});p.multicamGroups.push({id:'mc',name:'MC',angles:[{id:'a1',assetId:'a',sourceOffset:0,confidence:1},{id:'a2',assetId:'a',sourceOffset:0,confidence:1}],program:[{start:0,end:60,angleId:'a1'}]});const s=new V2ProjectSession(p),c=new StudioEditController(s);c.setTransform('root','c',{x:12,y:8});c.addEffect('root','c',{id:'fx1',type:'blur',enabled:true,params:{radius:2}});c.setEffectKeyframes('root','c','fx1','radius',[{frame:0,value:0,interpolation:'linear'},{frame:30,value:4,interpolation:'linear'}]);c.setBusGain('music',-6);c.switchMulticam('mc',10,20,'a2');assert.equal(s.project.compositions[0].tracks[0].clips[0].transform.x,12);assert.equal(s.project.compositions[0].tracks[0].clips[0].effectStack[0].keyframes?.radius.length,2);assert.equal(s.project.audioBuses.find(b=>b.id==='music')?.gainDb,-6);assert.equal(s.project.multicamGroups[0].program.some(x=>x.angleId==='a2'),true);assert.ok(s.project.checkpoints.length>=5);});
test('program monitor only consumes PreviewRenderer and repair controller returns localized lane',async()=>{const renderer={capabilities:async()=>({backend:'software' as const,available:true}),load:async()=>{},seek:async(frame:number)=>({frame,width:1,height:1,rgba:new Uint8Array(4)}),invalidate:async()=>{},dispose:async()=>{}};const m=new ProgramMonitorController(renderer);assert.equal((await m.seek(17)).frame,17);const r=RepairController.plan({id:'q',startFrame:10,endFrame:20,message:'bad caption',suggestion:'move it'});assert.deepEqual(r.range,{startFrame:10,endFrame:20});assert.equal(r.branchName,'repair/q');});

import { migrateV2ToV3, animated, defaultMotionTransform } from '../../../packages/schema/src/index.ts';
import { V3ProjectSession } from '../../../packages/timeline/src/index.ts';
import { StudioMotionController } from './controllers.ts';

test('motion controller commits through v3 typed operations and surfaces stale revisions',()=>{
 const p=migrateV2ToV3(migrateV1ToV2(v1));
 p.motionCompositions.push({id:'mc',name:'Motion',width:100,height:100,duration:60,background:'transparent',layers:[{id:'title',kind:'text',name:'Title',start:0,duration:60,enabled:true,locked:false,zIndex:0,transform:defaultMotionTransform(),opacity:animated(1),effects:[],masks:[],motionBlur:false,text:'Hi',textStyle:{fontSize:animated(20)}}]});
 const session=new V3ProjectSession(p),controller=new StudioMotionController(session),expected=session.revision;
 const ok=controller.setProperty(expected,'mc','title','opacity',.7);assert.equal(ok.ok,true);assert.equal(session.project.motionCompositions[0].layers[0].opacity.baseValue,.7);
 const stale=controller.setProperty(expected,'mc','title','opacity',.3);assert.equal(stale.ok,false);if(!stale.ok)assert.match(stale.conflict.message,/refresh/i);
});

test('motion controller edits curves rigs and layout using canonical operations',()=>{
 const p=migrateV2ToV3(migrateV1ToV2(v1));p.motionRigs.push({id:'rig',name:'Rig',version:1,controls:[{id:'amount',name:'Amount',type:'number',defaultValue:0,min:0,max:1}],bindings:[]});p.motionCompositions.push({id:'mc',name:'Motion',width:100,height:100,duration:60,background:'transparent',layers:[{id:'title',kind:'text',name:'Title',start:0,duration:60,enabled:true,locked:false,zIndex:0,transform:defaultMotionTransform(),opacity:animated(1),effects:[],masks:[],motionBlur:false,text:'Hi',textStyle:{fontSize:animated(20)}}]});
 const session=new V3ProjectSession(p),controller=new StudioMotionController(session);
 let r=controller.setKeyframes(session.revision,'mc','title','opacity',[{frame:0,value:0,interpolation:'linear'},{frame:10,value:1,interpolation:'ease'}]);assert.equal(r.ok,true);
 r=controller.setLayout(session.revision,'mc','title',[{id:'cx',type:'center-x'}]);assert.equal(r.ok,true);
 r=controller.setRigControl(session.revision,'rig','amount',.8);assert.equal(r.ok,true);assert.equal(session.project.motionRigs[0].controls[0].defaultValue,.8);
});

test('motion controller edits layer metadata timing parenting and supports undo redo without bypassing revisions',async()=>{
 const {migrateV1ToV2,migrateV2ToV3,animated,defaultMotionTransform}=await import('../../../packages/schema/src/index.ts');const {V3ProjectSession}=await import('../../../packages/timeline/src/v3.ts');const {StudioMotionController}=await import('./controllers.ts');
 const p=migrateV2ToV3(migrateV1ToV2({version:1,id:'u',name:'U',format:{width:640,height:360,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[],tracks:[],markers:[],style:{},provenance:[],checkpoints:[],branches:[]}));p.motionCompositions.push({id:'mc',name:'M',width:640,height:360,duration:120,background:'#000',layers:[{id:'a',kind:'shape',name:'A',start:0,duration:60,enabled:true,locked:false,zIndex:0,transform:defaultMotionTransform(),opacity:animated(1),effects:[],masks:[],motionBlur:false,shape:{kind:'rect',width:100,height:100}}]});const session=new V3ProjectSession(p),c=new StudioMotionController(session);let r=c.setLayerMetadata(session.revision,'mc','a',{name:'Hero',locked:false});assert.equal(r.ok,true);r=c.setLayerTiming(session.revision,'mc','a',12,80);assert.equal(r.ok,true);assert.equal(session.project.motionCompositions[0].layers[0].start,12);assert.equal(c.undo(session.revision).ok,true);assert.equal(session.project.motionCompositions[0].layers[0].start,0);assert.equal(c.redo(session.revision).ok,true);assert.equal(session.project.motionCompositions[0].layers[0].start,12);
});

test('motion controller commits direct mask and camera edits through typed v3 operations',async()=>{
 const {migrateV1ToV2,migrateV2ToV3,animated,defaultMotionTransform}=await import('../../../packages/schema/src/index.ts');const {V3ProjectSession}=await import('../../../packages/timeline/src/v3.ts');const {StudioMotionController}=await import('./controllers.ts');
 const p=migrateV2ToV3(migrateV1ToV2({version:1,id:'direct',name:'Direct',format:{width:640,height:360,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[],tracks:[],markers:[],style:{},provenance:[],checkpoints:[],branches:[]}));p.motionCompositions.push({id:'mc',name:'M',width:640,height:360,duration:120,background:'#000',layers:[{id:'shape',kind:'shape',name:'Shape',start:0,duration:120,enabled:true,locked:false,zIndex:0,transform:defaultMotionTransform(),opacity:animated(1),effects:[],masks:[{id:'m',kind:'rect',geometry:{kind:'rect',width:100,height:60},feather:animated(0),expansion:animated(0),invert:false,combine:'add'}],motionBlur:false,shape:{kind:'rect',width:100,height:100}},{id:'cam',kind:'camera',name:'Camera',start:0,duration:120,enabled:true,locked:false,zIndex:1,transform:defaultMotionTransform(),opacity:animated(1),effects:[],masks:[],motionBlur:false,camera:{focalLength:animated(50),focusDistance:animated(500),aperture:animated(2.8),depthOfField:animated(1)}}]});
 const s=new V3ProjectSession(p),c=new StudioMotionController(s);let r=c.setMask(s.revision,'mc','shape',{id:'m',kind:'rect',geometry:{kind:'rect',width:120,height:80},feather:animated(8),expansion:animated(2),invert:false,combine:'add'});assert.equal(r.ok,true);assert.equal((s.project.motionCompositions[0].layers[0].masks[0].geometry as any).width,120);r=c.setCamera(s.revision,'mc','cam',{focalLength:animated(85),focusDistance:animated(700),aperture:animated(1.8),depthOfField:animated(1)});assert.equal(r.ok,true);assert.equal(s.project.motionCompositions[0].layers[1].camera?.focalLength.baseValue,85);
});
