import type { AudioEffectInstance, Keyframe, Transform2D } from '../../../packages/schema/src/v2/project.ts';
import { V2ProjectSession, type V2EditOperation } from '../../../packages/timeline/src/index.ts';
import type { PreviewRenderer } from '../../../packages/render-preview/src/index.ts';
export class StudioEditController {private readonly session:V2ProjectSession;constructor(session:V2ProjectSession){this.session=session;}private apply(op:V2EditOperation){const r=this.session.apply(this.session.revision,op);if(!r.ok)throw new Error(r.conflict.message);return r.result;}setTransform(compositionId:string,clipId:string,transform:Partial<Transform2D>){return this.apply({type:'set_transform',compositionId,clipId,transform,intent:'Studio transform'});}setOpacity(compositionId:string,clipId:string,opacity:number){return this.apply({type:'set_opacity',compositionId,clipId,opacity,intent:'Studio opacity'});}addEffect(compositionId:string,clipId:string,effect:AudioEffectInstance){return this.apply({type:'add_effect',compositionId,clipId,effect,intent:'Studio add effect'});}reorderEffects(compositionId:string,clipId:string,effectIds:string[]){return this.apply({type:'reorder_effects',compositionId,clipId,effectIds,intent:'Studio reorder effects'});}setEffectKeyframes(compositionId:string,clipId:string,effectId:string,param:string,keyframes:Keyframe<unknown>[]){return this.apply({type:'set_keyframes',compositionId,clipId,effectId,param,keyframes,intent:'Studio keyframes'});}setBusGain(busId:string,gainDb:number){return this.apply({type:'set_audio_bus_gain',busId,gainDb,intent:'Studio mixer'});}setBusEffects(busId:string,effects:AudioEffectInstance[]){return this.apply({type:'set_audio_bus_effects',busId,effects,intent:'Studio bus effects'});}switchMulticam(groupId:string,start:number,end:number,angleId:string){return this.apply({type:'switch_multicam_angle',groupId,start,end,angleId,intent:'Studio multicam switch'});}}
export class ProgramMonitorController {private readonly renderer:PreviewRenderer;constructor(renderer:PreviewRenderer){this.renderer=renderer;}seek(frame:number){return this.renderer.seek(frame);}invalidate(start:number,end:number){return this.renderer.invalidate({start,end});}}
export interface RepairIssueLike{id:string;startFrame:number;endFrame:number;message:string;suggestion:string}
export class RepairController {static plan(issue:RepairIssueLike){return{branchName:`repair/${issue.id}`,range:{startFrame:issue.startFrame,endFrame:issue.endFrame},intent:`Repair ${issue.id}: ${issue.message}`,issueId:issue.id,suggestedAction:issue.suggestion};}}

import type { CameraDefinition, LayoutConstraint, MotionBehaviorInstance, MotionExpression, MotionKeyframe, MotionMaskDefinition, MotionCompositingGraph } from '../../../packages/schema/src/v3/project.ts';
import { V3ProjectSession, type V3EditOperation, type V3SessionApplyResult } from '../../../packages/timeline/src/v3.ts';
export class StudioMotionController {
 private readonly session:V3ProjectSession;
 constructor(session:V3ProjectSession){this.session=session;}
 private commit(expectedRevision:string,op:V3EditOperation):V3SessionApplyResult{return this.session.apply(expectedRevision,op);}
 setProperty(expectedRevision:string,compositionId:string,layerId:string,path:string,value:unknown){return this.commit(expectedRevision,{type:'set_motion_property',compositionId,layerId,path,value,intent:'Studio motion property'});}
 setKeyframes(expectedRevision:string,compositionId:string,layerId:string,path:string,keyframes:MotionKeyframe<unknown>[]){return this.commit(expectedRevision,{type:'set_motion_keyframes',compositionId,layerId,path,keyframes,intent:'Studio curve edit'});}
 setExpression(expectedRevision:string,compositionId:string,layerId:string,path:string,expression?:MotionExpression){return this.commit(expectedRevision,{type:'set_motion_expression',compositionId,layerId,path,expression,intent:'Studio expression'});}
 addBehavior(expectedRevision:string,compositionId:string,layerId:string,path:string,behavior:MotionBehaviorInstance){return this.commit(expectedRevision,{type:'add_motion_behavior',compositionId,layerId,path,behavior,intent:'Studio behavior'});}
 setLayout(expectedRevision:string,compositionId:string,layerId:string,constraints:LayoutConstraint[]){return this.commit(expectedRevision,{type:'set_layout_constraints',compositionId,layerId,constraints,intent:'Studio responsive layout'});}
 setRigControl(expectedRevision:string,rigId:string,controlId:string,value:unknown){return this.commit(expectedRevision,{type:'set_rig_control',rigId,controlId,value,intent:'Studio rig control'});}
 setLayerMetadata(expectedRevision:string,compositionId:string,layerId:string,metadata:{name?:string;locked?:boolean;enabled?:boolean;zIndex?:number}){return this.commit(expectedRevision,{type:'set_layer_metadata',compositionId,layerId,...metadata,intent:'Studio layer metadata'});}
 setLayerTiming(expectedRevision:string,compositionId:string,layerId:string,start:number,duration:number){return this.commit(expectedRevision,{type:'set_layer_timing',compositionId,layerId,start,duration,intent:'Studio layer timing'});}
 reparentLayer(expectedRevision:string,compositionId:string,layerId:string,parentId?:string){return this.commit(expectedRevision,{type:'reparent_motion_layer',compositionId,layerId,parentId,intent:'Studio layer reparent'});}

 setCompositingGraph(expectedRevision:string,compositionId:string,graph?:MotionCompositingGraph){return this.commit(expectedRevision,{type:'set_motion_graph',compositionId,graph,intent:'Studio compositing graph edit'});}
 setMask(expectedRevision:string,compositionId:string,layerId:string,mask:MotionMaskDefinition){return this.commit(expectedRevision,{type:'set_mask',compositionId,layerId,mask,intent:'Studio direct mask edit'});}
 setCamera(expectedRevision:string,compositionId:string,layerId:string,camera:CameraDefinition){return this.commit(expectedRevision,{type:'set_camera',compositionId,layerId,camera,intent:'Studio direct camera edit'});}
 undo(expectedRevision:string){return this.session.undo(expectedRevision);}
 redo(expectedRevision:string){return this.session.redo(expectedRevision);}
}
