import { DatabaseSync } from 'node:sqlite';
import { spawnSync } from 'node:child_process';
export type EvidenceKind='visual'|'ocr'|'region'|'track'|'transcript'|'audio';
export interface VisualEvidence {id:string;assetId:string;start:number;end:number;kind:EvidenceKind;text:string;confidence:number;provider:string;model:string;version:string;sourceHash:string;createdAt:string;metadata?:Record<string,unknown>}
export interface VisionCapabilities {provider:string;available:boolean;capabilities:string[];detail?:string}
export interface ImageFrame {width:number;height:number;rgba:Uint8Array}
export class EvidenceStore {private db:DatabaseSync;constructor(path=':memory:'){this.db=new DatabaseSync(path);this.db.exec(`CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL,start_tick INTEGER NOT NULL,end_tick INTEGER NOT NULL,kind TEXT NOT NULL,text_value TEXT NOT NULL,confidence REAL NOT NULL,provider TEXT NOT NULL,model TEXT NOT NULL,version TEXT NOT NULL,source_hash TEXT NOT NULL,created_at TEXT NOT NULL,metadata_json TEXT NOT NULL)`);}put(e:VisualEvidence){this.db.prepare(`INSERT OR REPLACE INTO evidence VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(e.id,e.assetId,e.start,e.end,e.kind,e.text,e.confidence,e.provider,e.model,e.version,e.sourceHash,e.createdAt,JSON.stringify(e.metadata??{}));}list(assetId?:string):VisualEvidence[]{const rows=(assetId?this.db.prepare('SELECT * FROM evidence WHERE asset_id=? ORDER BY start_tick,id').all(assetId):this.db.prepare('SELECT * FROM evidence ORDER BY asset_id,start_tick,id').all()) as any[];return rows.map(r=>({id:r.id,assetId:r.asset_id,start:r.start_tick,end:r.end_tick,kind:r.kind,text:r.text_value,confidence:r.confidence,provider:r.provider,model:r.model,version:r.version,sourceHash:r.source_hash,createdAt:r.created_at,metadata:JSON.parse(r.metadata_json)}));}invalidateSource(assetId:string,currentHash:string):number{const r=this.db.prepare('DELETE FROM evidence WHERE asset_id=? AND source_hash<>?').run(assetId,currentHash);return Number(r.changes);}close(){this.db.close();}}
export class LocalHistogramEmbeddingProvider {async capabilities():Promise<VisionCapabilities>{return{provider:'local-histogram',available:true,capabilities:['image-embedding']};}async embed(input:ImageFrame):Promise<number[]>{if(input.rgba.length!==input.width*input.height*4)throw new Error('invalid RGBA frame');const bins=new Array<number>(12).fill(0);for(let i=0;i<input.rgba.length;i+=4)for(let c=0;c<3;c++)bins[c*4+Math.min(3,Math.floor(input.rgba[i+c]/64))]++;const norm=Math.sqrt(bins.reduce((s,x)=>s+x*x,0))||1;return bins.map(x=>x/norm);}}
export class TesseractOcrProvider {async capabilities():Promise<VisionCapabilities>{const r=spawnSync('tesseract',['--version'],{encoding:'utf8'});return{provider:'tesseract',available:r.status===0,capabilities:r.status===0?['ocr']:[],detail:(r.stdout||r.stderr||'').split('\n')[0]};}async ocr(path:string):Promise<string>{const c=await this.capabilities();if(!c.available)throw new Error('tesseract unavailable');const r=spawnSync('tesseract',[path,'stdout','--psm','6'],{encoding:'utf8',timeout:30000});if(r.status!==0)throw new Error(r.stderr);return r.stdout.trim();}}
export interface PerceptionOptions {maxFrames:number}
export interface EvidenceTrace {evidence:VisualEvidence[];inspectedFrames:number[];trace:string[]}
function toks(s:string){return new Set(s.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(Boolean));}
export async function inspectForQuery(query:string,evidence:VisualEvidence[],options:PerceptionOptions):Promise<EvidenceTrace>{const trace=['metadata-index','rank-moments'];const q=toks(query);const scored=evidence.map(e=>({e,score:[...q].reduce((n,t)=>n+(toks(e.text).has(t)?1:0),0)*e.confidence})).sort((a,b)=>b.score-a.score||a.e.start-b.e.start);const chosen=scored.filter(x=>x.score>0).slice(0,Math.max(0,options.maxFrames));const frames=[...new Set(chosen.map(x=>Math.floor((x.e.start+x.e.end)/2)))].slice(0,options.maxFrames);if(chosen.length)trace.push('sparse-keyframes','focused-inspection');return{evidence:chosen.map(x=>x.e),inspectedFrames:frames,trace};}
