import type {GenerationProvider,GenerationRequest,ProviderCapabilityManifest,StagedGenerationOutput,StructuredHttpProviderOptions,VideoProviderCapabilities} from '../types.ts';
import {StructuredHttpProviderBase} from './structured-http.ts';

export interface LocalVideoHttpProviderOptions extends StructuredHttpProviderOptions{
 providerId?:string;
 defaultModel?:string;
 capabilities?:Partial<VideoProviderCapabilities>;
}

const defaults:VideoProviderCapabilities={supportsFirstFrame:true,supportsLastFrame:false,maxReferenceImages:1,supportsNegativePrompt:true,supportsSeed:true,minDurationSeconds:1,maxDurationSeconds:10,supportedResolutions:['480p','720p'],supportedAspectRatios:['16:9','9:16','1:1'],supportsCameraControl:false,supportsMotionMasks:false,supportsExtension:false,supportsNativeAudio:false};
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const asStrings=(v:unknown):string[]=>Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'&&x.length>0):[];
const controls=(request:GenerationRequest):Record<string,unknown>=>({...request.parameters,...(request.video??{})});

export class LocalVideoHttpProvider extends StructuredHttpProviderBase implements GenerationProvider{
 private readonly providerId:string;
 private readonly defaultModel:string;
 private video:VideoProviderCapabilities;
 constructor(options:LocalVideoHttpProviderOptions){super(options,'flicksmith-local-video');this.providerId=options.providerId?.trim()||'local-video-http';this.defaultModel=options.defaultModel?.trim()||'local-i2v';this.video={...defaults,...options.capabilities};}
 manifest():ProviderCapabilityManifest{return{provider:this.providerId,kinds:['video'],execution:'local',supportsTransparency:false,supportsMasks:this.video.supportsMotionMasks,supportsReferences:this.video.maxReferenceImages>0,supportsStreaming:false,supportsCancellation:true,video:structuredClone(this.video),models:[this.defaultModel],estimatedUnit:'second',estimatedCostUnits:0,metadata:{healthEndpoint:'/health',capabilitiesEndpoint:'/capabilities',generationEndpoint:'/v1/generate',freeLocal:true}}}
 async refreshCapabilities(signal?:AbortSignal):Promise<VideoProviderCapabilities>{const r=await this.fetchImpl(`${this.baseUrl}/capabilities`,{method:'GET',signal});if(!r.ok)throw new Error(`local video capabilities failed (${r.status})`);const raw=await r.json() as Partial<VideoProviderCapabilities>;this.video={...defaults,...raw,supportedResolutions:raw.supportedResolutions??this.video.supportedResolutions,supportedAspectRatios:raw.supportedAspectRatios??this.video.supportedAspectRatios};return structuredClone(this.video)}
 private check(request:GenerationRequest):void{if(request.kind!=='video')throw new Error('Local video provider only supports video generation');const p=controls(request),refs=asStrings(p.referenceAssetIds);if(refs.length>this.video.maxReferenceImages)throw new Error(`Local video worker supports at most ${this.video.maxReferenceImages} reference images`);if(typeof p.lastFrameAssetId==='string'&&!this.video.supportsLastFrame)throw new Error('Local video worker does not support last-frame guidance');if(typeof p.firstFrameAssetId==='string'&&!this.video.supportsFirstFrame)throw new Error('Local video worker does not support first-frame guidance');if(typeof p.negativePrompt==='string'&&!this.video.supportsNegativePrompt)throw new Error('Local video worker does not support negative prompts');if(request.seed!==undefined&&!this.video.supportsSeed)throw new Error('Local video worker does not support seeds');if(p.camera!==undefined&&!this.video.supportsCameraControl)throw new Error('Local video worker does not support camera control');if(asStrings(p.motionMaskAssetIds).length&&!this.video.supportsMotionMasks)throw new Error('Local video worker does not support motion masks');if(typeof p.extendVideoAssetId==='string'&&!this.video.supportsExtension)throw new Error('Local video worker does not support video extension');if(p.nativeAudio===true&&!this.video.supportsNativeAudio)throw new Error('Local video worker does not support native audio');if(finite(p.durationSeconds)){if(this.video.minDurationSeconds!==undefined&&p.durationSeconds<this.video.minDurationSeconds)throw new Error('Requested video duration is below worker minimum');if(this.video.maxDurationSeconds!==undefined&&p.durationSeconds>this.video.maxDurationSeconds)throw new Error('Requested video duration exceeds worker maximum')}if(typeof p.resolution==='string'&&this.video.supportedResolutions?.length&&!this.video.supportedResolutions.includes(p.resolution))throw new Error(`Unsupported video resolution ${p.resolution}`);if(typeof p.aspectRatio==='string'&&this.video.supportedAspectRatios?.length&&!this.video.supportedAspectRatios.includes(p.aspectRatio))throw new Error(`Unsupported video aspect ratio ${p.aspectRatio}`);}
 private async encoded(assetId:string,role:string){const v=await this.resolveInputAsset(assetId);return{assetId,role,mediaType:v.mediaType,dataBase64:Buffer.from(v.bytes).toString('base64'),width:v.width,height:v.height}}
 async generate(request:GenerationRequest,signal:AbortSignal):Promise<StagedGenerationOutput>{this.check(request);const p=controls(request),inputs:Array<Record<string,unknown>>=[];const first=typeof p.firstFrameAssetId==='string'?p.firstFrameAssetId:request.inputAssetIds[0];if(first)inputs.push(await this.encoded(first,'first-frame'));if(typeof p.lastFrameAssetId==='string')inputs.push(await this.encoded(p.lastFrameAssetId,'last-frame'));for(const id of asStrings(p.referenceAssetIds))inputs.push(await this.encoded(id,'reference'));for(const id of asStrings(p.motionMaskAssetIds))inputs.push(await this.encoded(id,'motion-mask'));if(typeof p.extendVideoAssetId==='string')inputs.push(await this.encoded(p.extendVideoAssetId,'extension-source'));const result=await this.post('/v1/generate',{requestId:request.id,model:request.model??this.defaultModel,prompt:request.prompt,negativePrompt:typeof p.negativePrompt==='string'?p.negativePrompt:undefined,seed:request.seed,controls:{durationSeconds:p.durationSeconds,resolution:p.resolution,aspectRatio:p.aspectRatio,camera:p.camera,candidateCount:p.candidateCount,nativeAudio:p.nativeAudio===true},inputs},signal);const raws=Array.isArray(result.outputs)?result.outputs:[result];if(raws.length===0)throw new Error('Local video worker returned no candidates');const outputs=raws.map((o:any,i:number)=>{if(typeof o.videoBase64!=='string'||!o.videoBase64.length)throw new Error(`Local video candidate ${i} is missing video data`);return{path:this.write(request.id,i,o.videoBase64,'.mp4'),mediaType:typeof o.mediaType==='string'?o.mediaType:'video/mp4',sha256:''}});return{requestId:request.id,provider:this.providerId,model:String(result.model??request.model??this.defaultModel),outputs,providerMetadata:{local:true,free:true,candidateCount:outputs.length,capabilities:this.video,...(result.metadata&&typeof result.metadata==='object'?result.metadata:{})},usage:{units:finite(p.durationSeconds)?p.durationSeconds*outputs.length:outputs.length,costUsd:0},rights:{commercialAllowed:null,attributionRequired:false,policy:'Local model license governs generated outputs'},createdAt:new Date().toISOString()}}
}
