export interface AudioSyncInput { reference:number[];referenceRate:number;candidate:number[];candidateRate:number;projectFps:number;maxOffsetSeconds:number }
export interface AudioSyncResult { offsetFrames:number;offsetSeconds:number;confidence:number;method:'audio-correlation';evidence:{score:number;sampleRate:number;lagSamples:number} }
function resample(src:number[],from:number,to:number):number[]{if(from===to)return [...src];const n=Math.max(1,Math.floor(src.length*to/from)),out=new Array<number>(n);for(let i=0;i<n;i++){const pos=i*from/to,j=Math.floor(pos),t=pos-j;out[i]=(src[j]??0)*(1-t)+(src[Math.min(src.length-1,j+1)]??0)*t;}return out;}
export function syncAudioOffset(input:AudioSyncInput):AudioSyncResult {if(input.referenceRate<=0||input.candidateRate<=0||input.projectFps<=0)throw new Error('rates must be positive');const rate=Math.max(1000,Math.min(16000,input.referenceRate,input.candidateRate)),a=resample(input.reference,input.referenceRate,rate),b=resample(input.candidate,input.candidateRate,rate);const maxLag=Math.min(Math.floor(input.maxOffsetSeconds*rate),Math.max(a.length,b.length)-1);let bestLag=0,best=-Infinity;for(let lag=-maxLag;lag<=maxLag;lag++){const a0=Math.max(0,-lag),b0=Math.max(0,lag),len=Math.min(a.length-a0,b.length-b0);if(len<Math.max(32,Math.floor(Math.min(a.length,b.length)*.2)))continue;let dot=0,aa=0,bb=0;for(let i=0;i<len;i++){const x=a[a0+i],y=b[b0+i];dot+=x*y;aa+=x*x;bb+=y*y;}const score=aa&&bb?dot/Math.sqrt(aa*bb):-1;if(score>best){best=score;bestLag=lag;}}if(!Number.isFinite(best))throw new Error('Unable to correlate audio');const seconds=bestLag/rate;return{offsetFrames:Math.round(seconds*input.projectFps),offsetSeconds:seconds,confidence:Math.max(0,Math.min(1,(best+1)/2)),method:'audio-correlation',evidence:{score:best,sampleRate:rate,lagSamples:bestLag}};}
export interface SyncAnchor {programFrame:number;sourceFrame:number}
export interface DriftModel {anchors:SyncAnchor[]}
export function buildDriftModel(anchors:SyncAnchor[]):DriftModel {if(anchors.length<2)throw new Error('At least two sync anchors required');const a=[...anchors].sort((x,y)=>x.programFrame-y.programFrame);for(let i=1;i<a.length;i++)if(a[i].programFrame<=a[i-1].programFrame)throw new Error('program anchors must increase');return{anchors:a};}
export function mapProgramFrameToSourceFrame(model:DriftModel,frame:number):number {const a=model.anchors;let i=1;while(i<a.length&&frame>a[i].programFrame)i++;const right=a[Math.min(i,a.length-1)],left=a[Math.max(0,Math.min(i-1,a.length-2))];const t=(frame-left.programFrame)/(right.programFrame-left.programFrame);return Math.round(left.sourceFrame+t*(right.sourceFrame-left.sourceFrame));}
export interface ProgramSegment {start:number;end:number;angleId:string}
export function switchProgramAngle(program:ProgramSegment[],start:number,end:number,angleId:string):ProgramSegment[]{if(!Number.isInteger(start)||!Number.isInteger(end)||end<=start)throw new Error('Invalid switch range');const out:ProgramSegment[]=[];for(const s of program){if(s.end<=start||s.start>=end){out.push({...s});continue;}if(s.start<start)out.push({start:s.start,end:start,angleId:s.angleId});out.push({start:Math.max(s.start,start),end:Math.min(s.end,end),angleId});if(s.end>end)out.push({start:end,end:s.end,angleId:s.angleId});}out.sort((a,b)=>a.start-b.start);const merged:ProgramSegment[]=[];for(const s of out){const last=merged.at(-1);if(last&&last.angleId===s.angleId&&last.end===s.start)last.end=s.end;else merged.push({...s});}return merged;}

import type { FlickProjectV2, V2Clip, V2Track } from '../../schema/src/v2/project.ts';
import { defaultTransform } from '../../schema/src/v2/project.ts';
export function materializeMulticamProgram(input:FlickProjectV2,groupId:string,compositionId:string,trackId:string):FlickProjectV2 {
 const p=structuredClone(input),group=p.multicamGroups.find(g=>g.id===groupId);if(!group)throw new Error(`Unknown multicam group ${groupId}`);const comp=p.compositions.find(c=>c.id===compositionId);if(!comp)throw new Error(`Unknown composition ${compositionId}`);let track=comp.tracks.find(t=>t.id===trackId);if(!track){track={id:trackId,kind:'video',name:group.name+' Program',clips:[]};comp.tracks.push(track);}if(track.kind!=='video')throw new Error('Multicam program target must be video track');
 const clips:V2Clip[]=group.program.map((seg,i)=>{const angle=group.angles.find(a=>a.id===seg.angleId);if(!angle)throw new Error(`Unknown multicam angle ${seg.angleId}`);let sourceStart=seg.start;if(angle.driftModel&&typeof angle.driftModel==='object'&&Array.isArray((angle.driftModel as any).anchors))sourceStart=mapProgramFrameToSourceFrame(angle.driftModel as DriftModel,seg.start);return{id:`${group.id}_${String(i).padStart(3,'0')}`,assetId:angle.assetId,start:seg.start,duration:seg.end-seg.start,sourceIn:angle.sourceOffset+sourceStart,transform:defaultTransform(),opacity:1,blendMode:'normal',maskRefs:[],effectStack:[],enabled:true,props:{multicamGroupId:group.id,angleId:angle.id}};});
 track.clips=clips;return p;
}
