import test from 'node:test';import assert from 'node:assert/strict';import {graphToScreen,screenToGraph,segmentControlPoints,handleToSpeedInfluence,speedInfluenceToHandle,copyCurveShape,pasteCurveShape} from '../math/curves.ts';

test('curve viewport pan zoom mapping round trips exact graph values',()=>{const v={frameMin:20,frameMax:80,valueMin:-50,valueMax:150,width:1200,height:600};for(const p of [{frame:20,value:-50},{frame:47.25,value:32.5},{frame:80,value:150}]){const s=graphToScreen(p,v),r=screenToGraph(s,v);assert.ok(Math.abs(r.frame-p.frame)<1e-9);assert.ok(Math.abs(r.value-p.value)<1e-9);}});

test('bezier control points map normalized keyframe handles to value graph geometry',()=>{const a={frame:10,value:20,interpolation:'bezier' as const,outTangent:{x:.25,y:.1}},b={frame:30,value:100,interpolation:'bezier' as const,inTangent:{x:.75,y:.9}};const c=segmentControlPoints(a,b);assert.deepEqual(c.p1,{frame:15,value:28});assert.deepEqual(c.p2,{frame:25,value:92});});

test('speed influence conversion round trips outgoing and incoming handles',()=>{for(const side of ['out','in'] as const){const h=side==='out'?{x:.2,y:.7}:{x:.8,y:.3};const si=handleToSpeedInfluence(h,side,0,120,0,60);const back=speedInfluenceToHandle(si,side,0,120,0,60);assert.ok(Math.abs(back.x-h.x)<1e-9);assert.ok(Math.abs(back.y-h.y)<1e-9);}});

test('curve shape clipboard changes interpolation without replacing keyframe values',()=>{const src=[{frame:0,value:0,interpolation:'bezier' as const,outTangent:{x:.1,y:.8}},{frame:10,value:10,interpolation:'bezier' as const,inTangent:{x:.9,y:.2}}];const dst=[{frame:40,value:500,interpolation:'linear' as const},{frame:80,value:900,interpolation:'linear' as const}];const out=pasteCurveShape(dst,copyCurveShape(src));assert.deepEqual(out.map(k=>k.value),[500,900]);assert.equal(out[0].interpolation,'bezier');assert.deepEqual(out[0].outTangent,{x:.1,y:.8});});

test('curve-shape transfer preserves animation samples across one thousand points',async()=>{const {evaluateAnimatedNumber}=await import('../../../../packages/animation/src/index.ts');const src=[{frame:0,value:0,interpolation:'bezier' as const,outTangent:{x:.18,y:.82}},{frame:100,value:1,interpolation:'bezier' as const,inTangent:{x:.82,y:.18}}];const dst=[{frame:0,value:0,interpolation:'linear' as const},{frame:100,value:1,interpolation:'linear' as const}];const pasted=pasteCurveShape(dst,copyCurveShape(src));for(let i=0;i<1000;i++){const frame=100*i/999;const a=evaluateAnimatedNumber({baseValue:0,keyframes:src},frame),b=evaluateAnimatedNumber({baseValue:0,keyframes:pasted},frame);assert.ok(Math.abs(a-b)<1e-10);}});
