import React,{useMemo,useRef} from 'react';
import type {AnimatedProperty,MotionInterpolation,MotionKeyframe} from '../../../../packages/schema/src/v3/project.ts';
import {graphToScreen,screenToGraph,sampleValueGraph,segmentControlPoints,handleToSpeedInfluence,type CurveViewport} from '../math/curves.ts';
export interface CurveEditorProps{property:AnimatedProperty<number>;viewport:CurveViewport;mode:'value'|'speed';selected:Set<number>;onSelect?:(frame:number,additive:boolean)=>void;onKeyframeChange?:(frame:number,next:MotionKeyframe<number>)=>void;onInterpolationChange?:(frame:number,kind:MotionInterpolation)=>void;onCopyCurveShape?:()=>void;onPasteCurveShape?:()=>void;onSeparateDimensions?:()=>void;}
type Drag={frame:number;side:'in'|'out';a:MotionKeyframe<number>;b:MotionKeyframe<number>};
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export function CurveEditor({property,viewport,mode,selected,onSelect,onKeyframeChange,onInterpolationChange,onCopyCurveShape,onPasteCurveShape,onSeparateDimensions}:CurveEditorProps){
 const keys=[...(property.keyframes??[])].sort((a,b)=>a.frame-b.frame);const drag=useRef<Drag|null>(null);
 const samples=useMemo(()=>sampleValueGraph(property,viewport.frameMin,viewport.frameMax,256),[property,viewport]);const sampleViewport=useMemo(()=>mode==='value'?viewport:{...viewport,valueMin:Math.min(...samples.map(s=>s.speed),-1e-6),valueMax:Math.max(...samples.map(s=>s.speed),1e-6)},[mode,viewport,samples]);
 const points=samples.map(s=>{const p=graphToScreen({frame:s.frame,value:mode==='value'?s.value:s.speed},sampleViewport);return`${p.x},${p.y}`}).join(' ');
 const updateHandle=(event:React.PointerEvent<SVGSVGElement>)=>{if(!drag.current||mode!=='value'||!onKeyframeChange)return;const r=event.currentTarget.getBoundingClientRect(),g=screenToGraph({x:(event.clientX-r.left)*viewport.width/r.width,y:(event.clientY-r.top)*viewport.height/r.height},viewport),{a,b,side,frame}=drag.current,dt=b.frame-a.frame,dv=b.value-a.value;if(dt<=0||Math.abs(dv)<1e-12)return;const normalized={x:clamp((g.frame-a.frame)/dt),y:(g.value-a.value)/dv};const target=keys.find(k=>k.frame===frame);if(!target)return;onKeyframeChange(frame,{...structuredClone(target),interpolation:'bezier',...(side==='out'?{outTangent:normalized}:{inTangent:normalized})});};
 return <section className="fs-section fs-curve-editor"><div className="fs-panel-title"><h3>{mode==='value'?'Value Graph':'Speed Graph'}</h3><div><button onClick={onCopyCurveShape}>Copy curve</button><button onClick={onPasteCurveShape}>Paste curve</button><button onClick={onSeparateDimensions}>Separate XYZ</button></div></div><svg viewBox={`0 0 ${viewport.width} ${viewport.height}`} role="img" aria-label={`${mode} curve editor`} onPointerMove={updateHandle} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2"/>{mode==='value'&&keys.slice(0,-1).map((a,i)=>{const b=keys[i+1],c=segmentControlPoints(a,b),out=graphToScreen(c.p1,viewport),incoming=graphToScreen(c.p2,viewport),ap=graphToScreen(c.p0,viewport),bp=graphToScreen(c.p3,viewport),outSI=handleToSpeedInfluence(a.outTangent??{x:1/3,y:1/3},'out',a.frame,b.frame,a.value,b.value),inSI=handleToSpeedInfluence(b.inTangent??{x:2/3,y:2/3},'in',a.frame,b.frame,a.value,b.value);return <g key={`handles-${a.frame}`} className="fs-curve-handles"><line x1={ap.x} y1={ap.y} x2={out.x} y2={out.y}/><line x1={bp.x} y1={bp.y} x2={incoming.x} y2={incoming.y}/><circle cx={out.x} cy={out.y} r="4" data-speed={outSI.speed} data-influence={outSI.influence} aria-label={`outgoing speed ${outSI.speed.toFixed(3)} influence ${outSI.influence.toFixed(1)}`} onPointerDown={e=>{drag.current={frame:a.frame,side:'out',a,b};e.currentTarget.setPointerCapture(e.pointerId)}}/><circle cx={incoming.x} cy={incoming.y} r="4" data-speed={inSI.speed} data-influence={inSI.influence} aria-label={`incoming speed ${inSI.speed.toFixed(3)} influence ${inSI.influence.toFixed(1)}`} onPointerDown={e=>{drag.current={frame:b.frame,side:'in',a,b};e.currentTarget.setPointerCapture(e.pointerId)}}/></g>})}{keys.map(k=>{const p=graphToScreen({frame:k.frame,value:mode==='value'?k.value:sampleValueGraph(property,k.frame-.001,k.frame+.001,2)[0].speed},sampleViewport);return <g key={k.frame}><circle cx={p.x} cy={p.y} r={selected.has(k.frame)?6:4} data-selected={selected.has(k.frame)} onClick={e=>onSelect?.(k.frame,e.metaKey||e.ctrlKey||e.shiftKey)}/><foreignObject x={p.x+8} y={Math.max(0,p.y-14)} width="132" height="28"><select aria-label={`Interpolation frame ${k.frame}`} value={k.interpolation} onChange={e=>onInterpolationChange?.(k.frame,e.target.value as MotionInterpolation)}>{['hold','linear','bezier','auto-bezier','continuous-bezier','ease','expo-in','expo-out','expo-in-out','spring','damped-overshoot'].map(i=><option key={i}>{i}</option>)}</select></foreignObject></g>})}</svg></section>;
}
