import React,{useMemo,useState} from 'react';
import {Background,Controls,Handle,MiniMap,Position,ReactFlow,type Connection,type Edge,type Node,type NodeProps} from '@xyflow/react';
import type {MotionCompositingGraph} from '../../../../packages/schema/src/v3/project.ts';
export interface NodePreview{kind:'native-render';resource:string;frame?:number}
export interface NodeGraphProps{graph:MotionCompositingGraph;renderNodePreview?:(nodeId:string)=>NodePreview|undefined;onConnect?:(from:string,to:string,inputIndex?:number)=>void;onDisconnect?:(from:string,to:string)=>void;onDelete?:(nodeId:string)=>void;onDuplicate?:(nodeId:string)=>void;onGroup?:(nodeIds:string[])=>void;onSelect?:(nodeId?:string)=>void}
type FlowData={label:string;kind:string;preview?:NodePreview};
function CompositorNode({data}:NodeProps<Node<FlowData>>){return <div className="fs-node"><Handle type="target" position={Position.Left}/><strong>{data.label}</strong><span>{data.kind}</span>{data.preview&&<small data-preview-resource={data.preview.resource}>native preview</small>}<Handle type="source" position={Position.Right}/></div>}
const nodeTypes={compositor:CompositorNode};
export function NodeGraph({graph,renderNodePreview,onConnect,onDisconnect,onDelete,onDuplicate,onGroup,onSelect}:NodeGraphProps){const[selected,setSelected]=useState<string[]>([]);const nodes=useMemo<Node<FlowData>[]>(()=>graph.nodes.map((n,i)=>({id:n.id,type:'compositor',position:{x:(i%4)*220,y:Math.floor(i/4)*130},data:{label:n.id,kind:n.kind,preview:renderNodePreview?.(n.id)}})),[graph,renderNodePreview]);const edges=useMemo<Edge[]>(()=>graph.nodes.flatMap(n=>n.inputs.map((source,i)=>({id:`${source}->${n.id}:${i}`,source,target:n.id,data:{inputIndex:i}}))),[graph]);const connect=(c:Connection)=>{if(c.source&&c.target)onConnect?.(c.source,c.target)};return <section className="fs-node-graph"><div className="fs-panel-title"><h3>Compositing</h3><div><button disabled={!selected.length} onClick={()=>onGroup?.(selected)}>Group</button><button disabled={selected.length!==1} onClick={()=>selected[0]&&onDuplicate?.(selected[0])}>Duplicate</button><button disabled={selected.length!==1} onClick={()=>selected[0]&&onDelete?.(selected[0])}>Delete</button></div></div><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onConnect={connect} onEdgesDelete={deleted=>deleted.forEach(e=>onDisconnect?.(e.source,e.target))} onSelectionChange={({nodes:n})=>{const ids=n.map(x=>x.id);setSelected(ids);onSelect?.(ids.length===1?ids[0]:undefined)}} fitView><Background/><MiniMap/><Controls/></ReactFlow></section>}
