import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { migrateV2ToV3, type FlickProjectV2 } from '../../schema/src/index.ts';
import { applyV3Operation } from '../../timeline/src/v3.ts';
import { buildGenerationAcceptance, type GenerationRequest, type StagedGenerationOutput } from '../src/index.ts';

function project(){const v2:FlickProjectV2={version:2,id:'p',name:'P',format:{width:100,height:100,fps:{numerator:30,denominator:1},audioSampleRate:48000},assets:[],rootCompositionId:'root',compositions:[{id:'root',name:'Root',width:100,height:100,tracks:[]}],audioBuses:[],multicamGroups:[],perception:{providers:[]},preview:{quality:'full',preferGpu:false},markers:[],style:{},provenance:[],checkpoints:[],branches:[]};return migrateV2ToV3(v2)}
test('accepted generation commits assets and immutable provenance atomically with content dedupe',()=>{const root=mkdtempSync(join(tmpdir(),'flick-accept-')),source=join(root,'stage.png');writeFileSync(source,'same');const request:GenerationRequest={id:'r1',projectId:'p',kind:'image',prompt:'hero',inputAssetIds:[],parameters:{quality:'high'},provider:'fake',model:'fixture'};const staged:StagedGenerationOutput={requestId:'r1',provider:'fake',model:'fixture',outputs:[{path:source,mediaType:'image/png',sha256:'0967115f2813a3541eaef77de9d9d577688e8a4d2d1fb7550d0c9cd3a6b9f7c1'}]};const a=buildGenerationAcceptance(request,staged,root);const result=applyV3Operation(project(),{type:'accept_generation',assets:a.assets,record:a.record,intent:'accept hero'});assert.equal(result.project.assets.length,1);assert.equal(result.project.generationRecords?.length,1);const second=applyV3Operation(result.project,{type:'accept_generation',assets:a.assets,record:{...a.record,id:'r2'},intent:'same bytes second request'});assert.equal(second.project.assets.length,1);assert.equal(second.project.generationRecords?.length,2)});
test('credential-bearing acceptance is rejected without changing input',()=>{const p=project(),before=structuredClone(p);assert.throws(()=>applyV3Operation(p,{type:'accept_generation',assets:[],record:{id:'bad',kind:'image',provider:'fake',model:'m',inputAssetIds:[],outputAssetIds:[],parameters:{token:'secret'},requestHash:'x',createdAt:new Date(0).toISOString()}} as any),/credential|token/i);assert.deepEqual(p,before)});
