import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {LocalVideoHttpProvider} from '../src/index.ts';

async function server(){const s=createServer(async(req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json'});res.end('{"ok":true}');return}if(req.url==='/capabilities'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({supportsFirstFrame:true,supportsLastFrame:true,maxReferenceImages:3,supportsNegativePrompt:true,supportsSeed:true,minDurationSeconds:1,maxDurationSeconds:12,supportedResolutions:['480p','720p'],supportedAspectRatios:['16:9'],supportsCameraControl:true,supportsMotionMasks:true,supportsExtension:true,supportsNativeAudio:false}));return}let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):{};if(req.url==='/v1/generate'){assert.equal(body.inputs[0].role,'first-frame');assert.equal(body.inputs[1].role,'last-frame');assert.equal(body.inputs[2].role,'reference');assert.equal(body.controls.durationSeconds,4);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({model:'wan-local-fixture',outputs:[{videoBase64:Buffer.from('video-a').toString('base64')},{videoBase64:Buffer.from('video-b').toString('base64')}],metadata:{backend:'fixture'}}));return}res.writeHead(404);res.end()});await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const a=s.address() as any;return{url:`http://127.0.0.1:${a.port}`,close:()=>new Promise<void>(r=>s.close(()=>r()))}}

test('local video provider discovers capabilities and stages multiple free local candidates',async()=>{const m=await server(),root=mkdtempSync(join(tmpdir(),'local-video-'));try{const p=new LocalVideoHttpProvider({baseUrl:m.url,stagingRoot:root,resolveInputAsset:async id=>({bytes:Buffer.from(id),mediaType:'image/png',width:1280,height:720})});const caps=await p.refreshCapabilities();assert.equal(caps.supportsLastFrame,true);assert.equal(p.manifest().execution,'local');assert.equal(p.manifest().estimatedCostUnits,0);const out=await p.generate({id:'v',projectId:'p',kind:'video',prompt:'premium bottle orbit',inputAssetIds:['first'],parameters:{lastFrameAssetId:'last',referenceAssetIds:['ref'],durationSeconds:4,resolution:'720p',aspectRatio:'16:9',camera:{orbitDegrees:15},candidateCount:2},seed:7},new AbortController().signal);assert.equal(out.outputs.length,2);assert.equal(readFileSync(out.outputs[0].path).toString(),'video-a');assert.equal(out.usage?.costUsd,0);assert.equal(out.providerMetadata?.local,true)}finally{await m.close();rmSync(root,{recursive:true,force:true})}});

test('local video provider fails instead of pretending unsupported controls exist',async()=>{const p=new LocalVideoHttpProvider({baseUrl:'http://127.0.0.1:1',capabilities:{supportsLastFrame:false,supportsCameraControl:false},resolveInputAsset:async()=>({bytes:Buffer.from('x'),mediaType:'image/png'})});await assert.rejects(()=>p.generate({id:'v',projectId:'p',kind:'video',inputAssetIds:['first'],parameters:{lastFrameAssetId:'last'}},new AbortController().signal),/last-frame/i);await assert.rejects(()=>p.generate({id:'v2',projectId:'p',kind:'video',inputAssetIds:['first'],parameters:{camera:{pan:'left'}}},new AbortController().signal),/camera control/i)});
